"""
Roadmap layer — structured nodes (Spec / Milestone / Task), never a document.

Source of truth is the graph; markdown is generated by roadmap_export (deterministic).
LLMs produce structured deltas (roadmap_apply ops), never rewrites.
Validation is a deterministic lint (schema, cross-refs, orphan milestones,
circular dependencies) — no LLM re-read.

Namespace: ROADMAP:SPEC:<n>, ROADMAP:MILESTONE:<n>, ROADMAP:TASK:<n>.
"""
from __future__ import annotations

import time

from ..db import get_graph
from ..schema import ensure_schema

# ---------------------------------------------------------------------------
# Schema constraints (deterministic lint reference)
# ---------------------------------------------------------------------------

KINDS = {
    "spec":      {"label": "Spec",      "prefix": "ROADMAP:SPEC",      "seq": "seq_spec"},
    "milestone": {"label": "Milestone", "prefix": "ROADMAP:MILESTONE", "seq": "seq_milestone"},
    "task":      {"label": "Task",      "prefix": "ROADMAP:TASK",      "seq": "seq_task"},
    # Canon Driven Development: detail nodes carrying the implementation
    # canon (API contracts, design decisions, constraints). A task points to
    # its canon via DETAILS edges; task_claim bundles them into the
    # dispatch-ready payload for the worker.
    "canon":     {"label": "Canon",     "prefix": "ROADMAP:CANON",     "seq": "seq_canon"},
}

STATUSES = {
    "spec":      {"draft", "active", "done", "obsolete"},
    "milestone": {"planned", "active", "done"},
    "task":      {"todo", "in_progress", "blocked", "done"},
    "canon":     {"draft", "active", "obsolete"},
}

# Whitelisted mutable fields per kind. claimed_* is deliberately absent from
# task — claims only move through task_claim/task_release (atomic, refusable).
FIELDS = {
    "spec":      {"title", "description", "status"},
    "milestone": {"title", "description", "status", "due"},
    # dod = Definition of Done, verified by the task-verify skill before
    # task_release(done=true); due = target date "YYYY-MM-DD".
    "task":      {"title", "description", "status", "type", "blocked_reason", "dod", "due"},
    "canon":     {"title", "description", "status"},
}

TASK_TYPES = {"feature", "bug", "doc", "test", "infra", "chore"}

EDGES = {
    # type: (allowed from-label, allowed to-label)
    "DEPENDS_ON": {("Task", "Task"), ("Spec", "Spec")},
    "IMPLEMENTS": {("Task", "Spec")},
    "PART_OF":    {("Task", "Milestone")},
    "DETAILS":    {("Canon", "Task"), ("Canon", "Spec")},
}

_LABELS = {v["label"] for v in KINDS.values()}


def _now() -> int:
    return int(time.time() * 1000)


def _kind_of(node_id: str) -> str | None:
    for kind, meta in KINDS.items():
        if node_id.startswith(meta["prefix"] + ":"):
            return kind
    return None


def _next_id(g, group_id: str, kind: str) -> str:
    seq = KINDS[kind]["seq"]
    res = g.query(
        f"""
        MERGE (p:Project {{group_id: $gid}})
        SET p.{seq} = coalesce(p.{seq}, 0) + 1
        RETURN p.{seq}
        """,
        {"gid": group_id},
    )
    return f"{KINDS[kind]['prefix']}:{res.result_set[0][0]}"


def _validate_fields(kind: str, fields: dict) -> str | None:
    """Write-time schema validation — the lint stays as a safety net, but
    invalid enums must never enter the graph (they vanish from backlog views)."""
    status = fields.get("status")
    if status is not None and status not in STATUSES[kind]:
        return f"invalid status '{status}' for {kind} (allowed: {sorted(STATUSES[kind])})"
    if kind == "task":
        ttype = fields.get("type")
        if ttype is not None and ttype not in TASK_TYPES:
            return f"invalid task type '{ttype}' (allowed: {sorted(TASK_TYPES)})"
        if fields.get("blocked_reason") and status is not None and status != "blocked":
            return "blocked_reason only makes sense with status 'blocked'"
    return None


def _get_node(g, node_id: str) -> dict | None:
    kind = _kind_of(node_id)
    if kind is None:
        return None
    label = KINDS[kind]["label"]
    res = g.query(f"MATCH (n:{label} {{id: $id}}) RETURN n", {"id": node_id})
    if not res.result_set:
        return None
    return dict(res.result_set[0][0].properties)


# ---------------------------------------------------------------------------
# roadmap_apply — structured deltas (patches), field-by-field merge
# ---------------------------------------------------------------------------

def roadmap_apply(
    group_id: str,
    ops: list[dict],
    author: str = "",
    worktree: str = "",
) -> dict:
    """Apply a structured patch. Each op is one of:
    {"op": "create", "kind": "spec|milestone|task", "fields": {...}}
    {"op": "update", "id": "...", "fields": {...}}   — merges field by field
    {"op": "delete", "id": "..."}
    {"op": "link",   "type": "DEPENDS_ON|IMPLEMENTS|PART_OF", "from": "...", "to": "..."}
    {"op": "unlink", "type": "...", "from": "...", "to": "..."}
    """
    ensure_schema(group_id)
    g = get_graph(group_id)
    now = _now()
    results: list[dict] = []

    for op in ops:
        try:
            results.append(_apply_one(g, group_id, op, author, worktree, now))
        except Exception as exc:
            results.append({"op": op.get("op"), "status": "error", "error": str(exc)})

    lint = roadmap_lint(group_id)
    return {"results": results, "lint": lint}


def _apply_one(g, group_id: str, op: dict, author: str, worktree: str, now: int) -> dict:
    action = op.get("op")

    if action == "create":
        kind = op.get("kind", "")
        if kind not in KINDS:
            return {"op": action, "status": "error", "error": f"unknown kind '{kind}'"}
        fields = op.get("fields") or {}
        bad = set(fields) - FIELDS[kind]
        if bad:
            return {"op": action, "status": "error",
                    "error": f"fields not allowed for {kind}: {sorted(bad)}"}
        invalid = _validate_fields(kind, fields)
        if invalid:
            return {"op": action, "status": "error", "error": invalid}
        node_id = _next_id(g, group_id, kind)
        label = KINDS[kind]["label"]
        default_status = {"spec": "draft", "milestone": "planned",
                          "task": "todo", "canon": "draft"}[kind]
        props = {
            "id": node_id,
            "group_id": group_id,
            "status": default_status,
            **fields,
            "author": author,
            "worktree": worktree,
            "created_at": now,
            "updated_at": now,
        }
        sets = ", ".join(f"n.{k} = ${k}" for k in props)
        g.query(f"CREATE (n:{label}) SET {sets}", props)
        return {"op": action, "status": "created", "id": node_id}

    if action == "update":
        node_id = op.get("id", "")
        kind = _kind_of(node_id)
        if kind is None:
            return {"op": action, "status": "error", "error": f"bad id '{node_id}'"}
        fields = op.get("fields") or {}
        bad = set(fields) - FIELDS[kind]
        if bad:
            return {"op": action, "status": "error",
                    "error": f"fields not allowed for {kind}: {sorted(bad)} "
                             "(claims go through task_claim)"}
        if not fields:
            return {"op": action, "status": "noop", "id": node_id}
        invalid = _validate_fields(kind, fields)
        if invalid:
            return {"op": action, "status": "error", "error": invalid}
        if kind == "task" and fields.get("status") == "done":
            return {"op": action, "status": "error",
                    "error": "tasks are marked done via task_release(done=true) "
                             "after their Definition of Done is verified, "
                             "not through roadmap_apply"}
        label = KINDS[kind]["label"]
        params = {"id": node_id, "now": now, "author": author, "worktree": worktree,
                  **{f"f_{k}": v for k, v in fields.items()}}
        sets = ", ".join(f"n.{k} = $f_{k}" for k in fields)
        # Leaving 'blocked' clears the stale reason (otherwise export/backlog
        # keep showing a ghost "blocked: ..." on a todo task).
        status = fields.get("status")
        if kind == "task" and status is not None and status != "blocked" \
                and "blocked_reason" not in fields:
            sets += ", n.blocked_reason = null"
        res = g.query(
            f"""
            MATCH (n:{label} {{id: $id}})
            SET {sets}, n.updated_at = $now, n.author = $author, n.worktree = $worktree
            RETURN n.id
            """,
            params,
        )
        if not res.result_set:
            return {"op": action, "status": "error", "error": f"node not found: {node_id}"}
        return {"op": action, "status": "updated", "id": node_id, "fields": sorted(fields)}

    if action == "delete":
        node_id = op.get("id", "")
        kind = _kind_of(node_id)
        if kind is None:
            return {"op": action, "status": "error", "error": f"bad id '{node_id}'"}
        label = KINDS[kind]["label"]
        eres = g.query(
            f"MATCH (n:{label} {{id: $id}})-[r]-() RETURN count(r)", {"id": node_id}
        )
        edges = eres.result_set[0][0] if eres.result_set else 0
        res = g.query(
            f"MATCH (n:{label} {{id: $id}}) DETACH DELETE n RETURN count(n)", {"id": node_id}
        )
        deleted = res.result_set[0][0] if res.result_set else 0
        out = {"op": action, "status": "deleted" if deleted else "not_found", "id": node_id}
        if deleted and edges:
            out["detached_edges"] = edges
        return out

    if action in ("link", "unlink"):
        etype = op.get("type", "")
        if etype not in EDGES:
            return {"op": action, "status": "error", "error": f"unknown edge type '{etype}'"}
        src, dst = op.get("from", ""), op.get("to", "")
        sk, dk = _kind_of(src), _kind_of(dst)
        if sk is None or dk is None:
            return {"op": action, "status": "error", "error": f"bad ids: {src} -> {dst}"}
        if src == dst:
            return {"op": action, "status": "error",
                    "error": f"self-referencing {etype} not allowed: {src}"}
        sl, dl = KINDS[sk]["label"], KINDS[dk]["label"]
        if (sl, dl) not in EDGES[etype]:
            return {"op": action, "status": "error",
                    "error": f"{etype} not allowed from {sl} to {dl}"}
        if action == "link":
            res = g.query(
                f"""
                MATCH (a:{sl} {{id: $src}}), (b:{dl} {{id: $dst}})
                MERGE (a)-[r:{etype}]->(b)
                SET r.created_at = coalesce(r.created_at, $now)
                RETURN count(r)
                """,
                {"src": src, "dst": dst, "now": now},
            )
            n = res.result_set[0][0] if res.result_set else 0
            return {"op": action, "status": "linked" if n else "error",
                    **({} if n else {"error": "one endpoint not found"}),
                    "edge": f"{src} -{etype}-> {dst}"}
        res = g.query(
            f"MATCH (:{sl} {{id: $src}})-[r:{etype}]->(:{dl} {{id: $dst}}) DELETE r RETURN count(r)",
            {"src": src, "dst": dst},
        )
        n = res.result_set[0][0] if res.result_set else 0
        return {"op": action, "status": "unlinked" if n else "not_found",
                "edge": f"{src} -{etype}-> {dst}"}

    return {"op": action, "status": "error", "error": f"unknown op '{action}'"}


# ---------------------------------------------------------------------------
# roadmap_lint — deterministic validation, no LLM
# ---------------------------------------------------------------------------

def roadmap_lint(group_id: str) -> dict:
    """Schema + cross-reference checks: bad status, missing title, orphan
    milestones, circular DEPENDS_ON, unclaimed in_progress tasks."""
    g = get_graph(group_id)
    errors: list[str] = []
    warnings: list[str] = []

    nodes: dict[str, dict] = {}
    for kind, meta in KINDS.items():
        res = g.query(f"MATCH (n:{meta['label']}) RETURN n")
        for (node,) in res.result_set:
            props = dict(node.properties)
            props["_kind"] = kind
            nodes[props.get("id", "?")] = props

    # Schema checks
    for nid, props in nodes.items():
        kind = props["_kind"]
        if not (props.get("title") or "").strip():
            errors.append(f"{nid}: missing title")
        status = props.get("status")
        if status not in STATUSES[kind]:
            errors.append(f"{nid}: invalid status '{status}' "
                          f"(allowed: {sorted(STATUSES[kind])})")
        if kind == "task":
            ttype = props.get("type")
            if ttype and ttype not in TASK_TYPES:
                warnings.append(f"{nid}: unknown task type '{ttype}' "
                                f"(known: {sorted(TASK_TYPES)})")
            if props.get("status") == "in_progress" and not props.get("claimed_by"):
                warnings.append(f"{nid}: in_progress but not claimed (use task_claim)")
            if props.get("status") == "blocked" and not props.get("blocked_reason"):
                warnings.append(f"{nid}: blocked without blocked_reason")
            if props.get("status") not in ("blocked", None) and props.get("blocked_reason"):
                warnings.append(f"{nid}: stale blocked_reason on a "
                                f"'{props.get('status')}' task")
            if props.get("status") == "done" and props.get("claimed_by"):
                warnings.append(f"{nid}: done but still claimed by "
                                f"{props.get('claimed_by')} (release it)")

    # Edges
    deps: dict[str, list[str]] = {}
    res = g.query("MATCH (a)-[:DEPENDS_ON]->(b) RETURN a.id, b.id")
    for src, dst in res.result_set:
        deps.setdefault(src, []).append(dst)

    implements: set[str] = set()
    res = g.query("MATCH (t:Task)-[:IMPLEMENTS]->(:Spec) RETURN t.id")
    implements.update(r[0] for r in res.result_set)

    milestones_with_tasks: set[str] = set()
    res = g.query("MATCH (:Task)-[:PART_OF]->(m:Milestone) RETURN DISTINCT m.id")
    milestones_with_tasks.update(r[0] for r in res.result_set)

    attached_canon: set[str] = set()
    res = g.query("MATCH (c:Canon)-[:DETAILS]->() RETURN DISTINCT c.id")
    attached_canon.update(r[0] for r in res.result_set)

    # Orphan milestones / detached canon
    for nid, props in nodes.items():
        if props["_kind"] == "milestone" and nid not in milestones_with_tasks:
            errors.append(f"{nid}: orphan milestone (no task PART_OF it)")
        if props["_kind"] == "task" and nid not in implements:
            warnings.append(f"{nid}: task implements no spec")
        if props["_kind"] == "canon" and nid not in attached_canon:
            warnings.append(f"{nid}: canon node DETAILS nothing (link it to a task or spec)")

    # Circular DEPENDS_ON (iterative DFS, white/grey/black)
    WHITE, GREY, BLACK = 0, 1, 2
    color = {nid: WHITE for nid in nodes}
    for start in list(nodes):
        if color.get(start) != WHITE:
            continue
        stack = [(start, iter(deps.get(start, [])))]
        color[start] = GREY
        while stack:
            nid, it = stack[-1]
            nxt = next(it, None)
            if nxt is None:
                color[nid] = BLACK
                stack.pop()
                continue
            if color.get(nxt, WHITE) == GREY:
                errors.append(f"circular DEPENDS_ON involving {nxt}")
            elif color.get(nxt, WHITE) == WHITE:
                color[nxt] = GREY
                stack.append((nxt, iter(deps.get(nxt, []))))

    # Done task depending on an unfinished task
    for src, dsts in deps.items():
        if nodes.get(src, {}).get("status") == "done":
            for dst in dsts:
                if nodes.get(dst, {}).get("status") not in (None, "done"):
                    warnings.append(f"{src}: done but depends on unfinished {dst}")

    return {"ok": not errors, "errors": errors, "warnings": warnings,
            "nodes": len(nodes)}


# ---------------------------------------------------------------------------
# task_claim / task_release — multi-worktree coordination
# ---------------------------------------------------------------------------

def task_claim(task_id: str, group_id: str, user: str, worktree: str) -> dict:
    """Atomically claim a task. Refuses if already claimed by someone else."""
    g = get_graph(group_id)
    now = _now()
    current = _get_node(g, task_id)
    if current is None:
        return {"status": "error", "error": f"task not found: {task_id}"}
    if current.get("status") == "done":
        return {"status": "refused", "id": task_id,
                "error": "task is already done; reopen it first "
                         "(roadmap_apply update status='todo') if it needs rework"}
    holder = current.get("claimed_by")
    if holder and not (holder == user and current.get("claimed_worktree") == worktree):
        return {
            "status": "refused",
            "id": task_id,
            "claimed_by": holder,
            "claimed_worktree": current.get("claimed_worktree"),
            "claimed_at": current.get("claimed_at"),
        }
    g.query(
        """
        MATCH (t:Task {id: $id})
        SET t.claimed_by = $user,
            t.claimed_worktree = $wt,
            t.claimed_at = $now,
            t.status = CASE WHEN t.status = 'todo' THEN 'in_progress' ELSE t.status END,
            t.updated_at = $now
        """,
        {"id": task_id, "user": user, "wt": worktree, "now": now},
    )
    return {"status": "claimed", "id": task_id, "by": user, "worktree": worktree,
            **_dispatch_payload(g, task_id, current)}


def _dispatch_payload(g, task_id: str, task_props: dict) -> dict:
    """Canon-Driven-Development bundle returned by task_claim: everything the
    orchestrator forwards to a worker, no extra round-trips."""
    res = g.query(
        """
        MATCH (t:Task {id: $id})
        OPTIONAL MATCH (c:Canon)-[:DETAILS]->(t)
        OPTIONAL MATCH (t)-[:DEPENDS_ON]->(d:Task)
        RETURN collect(DISTINCT c), collect(DISTINCT d.id)
        """,
        {"id": task_id},
    )
    canon_nodes, dep_ids = res.result_set[0] if res.result_set else ([], [])
    canon = []
    for node in canon_nodes:
        p = dict(node.properties)
        if p.get("status") == "obsolete":
            continue
        canon.append({"id": p.get("id"), "title": p.get("title"),
                      "description": p.get("description")})
    canon.sort(key=lambda c: c["id"] or "")
    return {
        "task": {k: task_props.get(k)
                 for k in ("title", "description", "type", "dod", "due")},
        "canon": canon,
        "depends_on": sorted(d for d in dep_ids if d),
    }


def task_release(task_id: str, group_id: str, user: str, done: bool = False) -> dict:
    """Release a claim; done=True also marks the task done."""
    g = get_graph(group_id)
    now = _now()
    current = _get_node(g, task_id)
    if current is None:
        return {"status": "error", "error": f"task not found: {task_id}"}
    holder = current.get("claimed_by")
    if holder and holder != user:
        return {"status": "refused", "id": task_id, "claimed_by": holder}
    if done and holder != user:
        return {"status": "refused", "id": task_id,
                "error": "done=true requires holding the claim — "
                         "task_claim it first, verify the Definition of Done, "
                         "then release"}
    g.query(
        """
        MATCH (t:Task {id: $id})
        SET t.claimed_by = null,
            t.claimed_worktree = null,
            t.claimed_at = null,
            t.status = CASE WHEN $done THEN 'done'
                            WHEN t.status = 'in_progress' THEN 'todo'
                            ELSE t.status END,
            t.updated_at = $now
        """,
        {"id": task_id, "done": done, "now": now},
    )
    return {"status": "released", "id": task_id, "done": done}


def task_link_code(task_id: str, group_id: str, symbols: list[str]) -> dict:
    """Link a task to the code it produced: (:Task)-[:PRODUCED]->(:CodeChunk).

    Called by the orchestrator when a task completes, with the symbols the
    worker reported (module.func / module.Class.method). Symbols not found in
    the code index (not yet ingested, or misreported) come back in `missing`
    — they are NOT an error, retry after the next reindex if needed."""
    g = get_graph(group_id)
    now = _now()
    if _get_node(g, task_id) is None:
        return {"status": "error", "error": f"task not found: {task_id}"}

    linked: list[str] = []
    missing: list[str] = []
    for sym in symbols:
        if not sym:
            continue
        res = g.query(
            """
            MATCH (t:Task {id: $tid})
            MATCH (c:CodeChunk {symbol: $sym, valid: true})
            MERGE (t)-[r:PRODUCED]->(c)
            SET r.created_at = coalesce(r.created_at, $now)
            RETURN count(r)
            """,
            {"tid": task_id, "sym": sym, "now": now},
        )
        n = res.result_set[0][0] if res.result_set else 0
        (linked if n else missing).append(sym)

    return {"status": "ok", "id": task_id, "linked": linked, "missing": missing}


# ---------------------------------------------------------------------------
# backlog — persistent structured progress state
# ---------------------------------------------------------------------------

def backlog_get(group_id: str, include_done: bool = False) -> dict:
    """Tasks grouped by status with claims + milestone progress. A session
    resumes exactly where the previous one stopped."""
    ensure_schema(group_id)
    g = get_graph(group_id)

    res = g.query(
        """
        MATCH (t:Task)
        OPTIONAL MATCH (t)-[:PART_OF]->(m:Milestone)
        OPTIONAL MATCH (t)-[:IMPLEMENTS]->(s:Spec)
        OPTIONAL MATCH (t)-[:DEPENDS_ON]->(d:Task)
        RETURN t, m.id, collect(DISTINCT s.id), collect(DISTINCT d.id)
        """
    )
    by_status: dict[str, list[dict]] = {}
    for node, mid, spec_ids, dep_ids in res.result_set:
        p = dict(node.properties)
        status = p.get("status", "todo")
        if status == "done" and not include_done:
            continue
        by_status.setdefault(status, []).append({
            "id": p.get("id"),
            "title": p.get("title"),
            "type": p.get("type"),
            "status": status,
            "claimed_by": p.get("claimed_by"),
            "claimed_worktree": p.get("claimed_worktree"),
            "blocked_reason": p.get("blocked_reason"),
            "milestone": mid,
            "implements": [s for s in spec_ids if s],
            "depends_on": [d for d in dep_ids if d],
        })
    for tasks in by_status.values():
        tasks.sort(key=lambda t: t["id"] or "")

    mres = g.query(
        """
        MATCH (m:Milestone)
        OPTIONAL MATCH (t:Task)-[:PART_OF]->(m)
        RETURN m.id, m.title, m.status,
               count(t), count(CASE WHEN t.status = 'done' THEN 1 END)
        ORDER BY m.id
        """
    )
    milestones = [
        {"id": r[0], "title": r[1], "status": r[2], "tasks": r[3], "done": r[4]}
        for r in mres.result_set
    ]
    return {"tasks": by_status, "milestones": milestones}


# ---------------------------------------------------------------------------
# impact — Cypher query, not a re-read
# ---------------------------------------------------------------------------

def roadmap_impact(node_id: str, group_id: str) -> dict:
    """What is affected if *node_id* changes: tasks implementing a spec,
    tasks depending (transitively) on a task, dependent specs."""
    g = get_graph(group_id)
    kind = _kind_of(node_id)
    if kind is None:
        return {"error": f"bad id '{node_id}'"}

    out: dict = {"id": node_id}
    if kind == "spec":
        res = g.query(
            """
            MATCH (s:Spec {id: $id})<-[:IMPLEMENTS]-(t:Task)
            RETURN t.id, t.title, t.status, t.claimed_by ORDER BY t.id
            """,
            {"id": node_id},
        )
        out["implementing_tasks"] = [
            {"id": r[0], "title": r[1], "status": r[2], "claimed_by": r[3]}
            for r in res.result_set
        ]
        res = g.query(
            "MATCH (s:Spec {id: $id})<-[:DEPENDS_ON*1..5]-(d:Spec) "
            "RETURN DISTINCT d.id, d.title, d.status",
            {"id": node_id},
        )
        out["dependent_specs"] = [
            {"id": r[0], "title": r[1], "status": r[2]} for r in res.result_set
        ]
    else:
        res = g.query(
            "MATCH (t:Task {id: $id})<-[:DEPENDS_ON*1..5]-(d:Task) "
            "RETURN DISTINCT d.id, d.title, d.status, d.claimed_by",
            {"id": node_id},
        )
        out["dependent_tasks"] = [
            {"id": r[0], "title": r[1], "status": r[2], "claimed_by": r[3]}
            for r in res.result_set
        ]
        # Code produced by this task (PRODUCED edges written at task
        # completion) — what to re-inspect when the task's canon changes.
        res = g.query(
            "MATCH (t:Task {id: $id})-[:PRODUCED]->(c:CodeChunk {valid: true}) "
            "RETURN c.symbol, c.path ORDER BY c.symbol",
            {"id": node_id},
        )
        out["produced_code"] = [
            {"symbol": r[0], "path": r[1]} for r in res.result_set
        ]
    return out


# ---------------------------------------------------------------------------
# roadmap_export — deterministic markdown generation
# ---------------------------------------------------------------------------

_STATUS_MARK = {"todo": " ", "in_progress": "~", "blocked": "!", "done": "x"}


def _seq(node_id: str) -> int:
    try:
        return int(node_id.rsplit(":", 1)[1])
    except Exception:
        return 0


def roadmap_export(group_id: str) -> str:
    """Generate the roadmap markdown from the graph. Never hand-edited —
    regenerate after every roadmap_apply."""
    g = get_graph(group_id)

    specs = {}
    for (n,) in g.query("MATCH (s:Spec) RETURN s").result_set:
        specs[n.properties["id"]] = dict(n.properties)
    milestones = {}
    for (n,) in g.query("MATCH (m:Milestone) RETURN m").result_set:
        milestones[n.properties["id"]] = dict(n.properties)
    tasks = {}
    for (n,) in g.query("MATCH (t:Task) RETURN t").result_set:
        tasks[n.properties["id"]] = dict(n.properties)

    part_of: dict[str, str] = {}
    for src, dst in g.query(
        "MATCH (t:Task)-[:PART_OF]->(m:Milestone) RETURN t.id, m.id"
    ).result_set:
        part_of[src] = dst
    impl: dict[str, list[str]] = {}
    for src, dst in g.query(
        "MATCH (t:Task)-[:IMPLEMENTS]->(s:Spec) RETURN t.id, s.id"
    ).result_set:
        impl.setdefault(src, []).append(dst)
    deps: dict[str, list[str]] = {}
    for src, dst in g.query(
        "MATCH (a)-[:DEPENDS_ON]->(b) RETURN a.id, b.id"
    ).result_set:
        deps.setdefault(src, []).append(dst)

    lines: list[str] = ["# Roadmap", "",
                        "<!-- Generated from the graph by roadmap_export. Do NOT edit by hand. -->",
                        ""]

    def _task_line(tid: str) -> str:
        t = tasks[tid]
        mark = _STATUS_MARK.get(t.get("status", "todo"), " ")
        extra = []
        if impl.get(tid):
            extra.append("implements " + ", ".join(sorted(impl[tid], key=_seq)))
        if deps.get(tid):
            extra.append("depends on " + ", ".join(sorted(deps[tid], key=_seq)))
        if t.get("claimed_by"):
            extra.append(f"claimed by {t['claimed_by']}")
        if t.get("blocked_reason"):
            extra.append(f"blocked: {t['blocked_reason']}")
        suffix = f" _({'; '.join(extra)})_" if extra else ""
        return f"- [{mark}] `{tid}` {t.get('title', '')}{suffix}"

    if specs:
        lines += ["## Specs", ""]
        for sid in sorted(specs, key=_seq):
            s = specs[sid]
            dep = ""
            if deps.get(sid):
                dep = " — depends on " + ", ".join(sorted(deps[sid], key=_seq))
            lines.append(f"- `{sid}` **{s.get('title', '')}** [{s.get('status')}]{dep}")
            if s.get("description"):
                lines.append(f"  - {s['description']}")
        lines.append("")

    for mid in sorted(milestones, key=_seq):
        m = milestones[mid]
        lines += [f"## {m.get('title', mid)} (`{mid}`, {m.get('status')})", ""]
        if m.get("description"):
            lines += [m["description"], ""]
        for tid in sorted((t for t, mm in part_of.items() if mm == mid), key=_seq):
            lines.append(_task_line(tid))
        lines.append("")

    unattached = sorted((t for t in tasks if t not in part_of), key=_seq)
    if unattached:
        lines += ["## Backlog (no milestone)", ""]
        lines += [_task_line(tid) for tid in unattached]
        lines.append("")

    return "\n".join(lines)
