// Agents info model: pure functions, without `$`, tested on their own.
// Event and field names come from the declarations generated by the engine
// (`.claude/types/claude-code/index.d.ts`, Claude Code 2.1.287) — none is invented.

import type {
  AgentRun,
  Alert,
  Bucket,
  Effort,
  Forecast,
  Instance,
  Limit,
  Options,
  Plan,
  PlanState,
  PlanStep,
  Prompt,
  Recap,
  Status,
  TimelineEntry,
  Tokens,
  Usage,
} from '../types'

export type { AgentRun, Alert, Bucket, Effort, Forecast, Instance, Limit, Options, Plan, PlanState, PlanStep, Prompt, Recap, Status, TimelineEntry, Tokens, Usage }

export const MAIN = 'main'


export const DEFAULT_OPTIONS: Options = {
  limitWarn: 80,
  limitCritical: 95,
  agentTokenLimit: 0,
  sessionTokenLimit: 0,
  mainShareLimit: 0,
  modelMismatch: true,
}

const MAX_PROMPTS = 50
const MAX_TIMELINE = 300
const MAX_RUNS = 200
const MAIN_SHARE_FLOOR = 20000
const TASK_NOTIFICATION = '<task-notification>'

export const zero = (): Tokens => ({ input: 0, output: 0, cacheRead: 0, cacheWrite: 0 })

export function emptyRecap(): Recap {
  return {
    surface: null,
    startAgent: 'default',
    plan: null,
    runs: {},
    order: [],
    prompts: [],
    timeline: [],
    buckets: {},
    limits: {},
    costUsd: null,
    alerted: [],
  }
}

function currentPrompt(s: Recap): number {
  return s.prompts.length === 0 ? 0 : s.prompts[s.prompts.length - 1]!.index
}

function withRun(s: Recap, run: AgentRun): Recap {
  const isNew = s.runs[run.id] === undefined
  const order = isNew ? [...s.order, run.id].slice(-MAX_RUNS) : s.order
  const runs: Record<string, AgentRun> = {}
  for (const id of order) runs[id] = id === run.id ? run : s.runs[id]!
  return { ...s, runs, order }
}

function pushTimeline(s: Recap, entry: TimelineEntry): Recap {
  return { ...s, timeline: [...s.timeline, entry].slice(-MAX_TIMELINE) }
}

export function effortOf(effort: unknown): Effort {
  if (typeof effort === 'number') return `${effort} tok`
  if (typeof effort === 'string' && effort !== '') return effort
  return '—'
}

/** `agent` setting absent or set to "default": the starting agent is not named. */
const PLACEHOLDER_AGENT = /^(default|)$/i

export function onSessionStart(
  s: Recap,
  e: { surface: string | null; agent: string | undefined; model: string; at: number },
): Recap {
  // never inferred: the main agent, the scribe and the orchestrator are three peers (CANON:17)
  const startAgent = e.agent !== undefined && !PLACEHOLDER_AGENT.test(e.agent) ? e.agent : 'default'
  const main: AgentRun = s.runs[MAIN] ?? {
    id: MAIN,
    parentId: null,
    agent: startAgent,
    promptIndex: 0,
    instance: 'new',
    model: e.model,
    effort: '—',
    status: 'running',
    resumes: 0,
    startedAt: e.at,
    activeSince: e.at,
    activeMs: 0,
    tokens: zero(),
  }
  return withRun({ ...s, surface: e.surface, startAgent }, { ...main, agent: startAgent, model: e.model })
}

/** A user prompt; background task notifications are not prompts. */
export function onPrompt(s: Recap, e: { text: string; at: number }): Recap {
  if (e.text.startsWith(TASK_NOTIFICATION)) return s
  const index = currentPrompt(s) + 1
  const prompt = { index, text: e.text.replace(/\s+/g, ' ').slice(0, 80), at: e.at }
  return { ...s, prompts: [...s.prompts, prompt].slice(-MAX_PROMPTS) }
}

export function onSpawn(
  s: Recap,
  e: { agentId: string; parentId?: string; agent: string; model: string; fork: boolean; at: number; task?: string },
): Recap {
  const known = s.runs[e.agentId]
  const kind: Instance = known !== undefined ? 'resumed' : e.fork ? 'fork' : 'new'
  const isIdle = known === undefined || known.status !== 'running'
  const promptIndex = currentPrompt(s)
  const run: AgentRun = {
    id: e.agentId,
    parentId: e.parentId ?? MAIN,
    agent: e.agent,
    promptIndex: known?.promptIndex ?? promptIndex,
    instance: known?.instance ?? kind,
    spawnModel: e.model,
    model: e.model,
    effort: known?.effort ?? '—',
    task: (e.task ?? '').replace(/\s+/g, ' ').trim().slice(0, 80) || known?.task,
    stepIndex: known?.stepIndex ?? runningStep(s),
    status: 'running',
    resumes: (known?.resumes ?? 0) + (known !== undefined ? 1 : 0),
    startedAt: known?.startedAt ?? e.at,
    activeSince: isIdle ? e.at : (known.activeSince ?? known.startedAt),
    activeMs: known?.activeMs ?? 0,
    tokens: known?.tokens ?? zero(),
    ...(known?.mascot !== undefined ? { mascot: known.mascot } : {}),
  }
  let withPlan = s
  if (known === undefined && run.stepIndex !== undefined) withPlan = bumpStep(s, run.stepIndex, 'started')
  return pushTimeline(withRun(withPlan, run), { promptIndex, agentId: e.agentId, kind, at: e.at })
}

/**
 * A model call of an agent. An unknown agent (launched before the Mod loaded) is
 * created; an agent that has finished and speaks again was resumed (SendMessage): no `agent.spawn`.
 */
export function onStep(
  s: Recap,
  e: { agentId?: string; model: string; effort: unknown; at: number },
): Recap {
  const id = e.agentId ?? MAIN
  const effort = effortOf(e.effort)
  const run = s.runs[id]
  const promptIndex = currentPrompt(s)
  if (run === undefined) {
    const created: AgentRun = {
      id,
      parentId: id === MAIN ? null : MAIN,
      agent: id === MAIN ? s.startAgent : 'unknown',
      promptIndex,
      instance: 'resumed',
      model: e.model,
      effort,
      status: 'running',
      resumes: 0,
      startedAt: e.at,
      activeSince: e.at,
      activeMs: 0,
      tokens: zero(),
    }
    const next = withRun(s, created)
    return id === MAIN ? next : pushTimeline(next, { promptIndex, agentId: id, kind: 'resumed', at: e.at })
  }
  const isResumed = id !== MAIN && run.status !== 'running'
  const updated: AgentRun = {
    ...run,
    model: e.model,
    effort,
    status: 'running',
    resumes: run.resumes + (isResumed ? 1 : 0),
    endedAt: isResumed ? undefined : run.endedAt,
    ...(isResumed ? { activeSince: e.at } : {}),
  }
  const next = withRun(s, updated)
  return isResumed ? pushTimeline(next, { promptIndex, agentId: id, kind: 'resumed', at: e.at }) : next
}


function add(a: Tokens, u: Usage): Tokens {
  return {
    input: a.input + u.input_tokens,
    output: a.output + u.output_tokens,
    cacheRead: a.cacheRead + u.cache_read_input_tokens,
    cacheWrite: a.cacheWrite + u.cache_creation_input_tokens,
  }
}

/** Usage of a model call (`stop` chunk of `turn.step`), attributed to agent × model × effort. */
export function onUsage(s: Recap, e: { agentId?: string; effort: unknown; usage: Usage }): Recap {
  const id = e.agentId ?? MAIN
  const run = s.runs[id]
  const agent = run?.agent ?? (id === MAIN ? s.startAgent : 'unknown')
  const effort = effortOf(e.effort)
  const key = `${agent}\u0000${e.usage.model}\u0000${effort}`
  const bucket = s.buckets[key] ?? { agent, model: e.usage.model, effort, tokens: zero(), calls: 0 }
  const buckets = { ...s.buckets, [key]: { ...bucket, tokens: add(bucket.tokens, e.usage), calls: bucket.calls + 1 } }
  const next = { ...s, buckets }
  return run === undefined ? next : withRun(next, { ...run, tokens: add(run.tokens, e.usage) })
}

export function onComplete(s: Recap, e: { agentId?: string; reason: string; at: number }): Recap {
  const id = e.agentId ?? MAIN
  const run = s.runs[id]
  if (run === undefined || id === MAIN) return s
  const status: Status = e.reason === 'error' ? 'failed' : 'done'
  const base = run.status === 'running' && run.stepIndex !== undefined ? bumpStep(s, run.stepIndex, 'finished') : s
  // the stretch that ends is added to the worked time; a second completion adds nothing
  const activeMs = (run.activeMs ?? 0) + (run.status === 'running' ? Math.max(0, e.at - (run.activeSince ?? run.startedAt)) : 0)
  return withRun(base, { ...run, status, endedAt: e.at, activeMs })
}

/**
 * Time an agent has actually worked: its finished stretches plus the current one. A resumed agent does not count
 * the time it spent waiting between two runs. A run recorded before this field existed falls back to its span.
 */
export function workedMs(r: AgentRun, now: number): number {
  if (r.activeMs === undefined && r.activeSince === undefined) return (r.endedAt ?? now) - r.startedAt
  return (r.activeMs ?? 0) + (r.status === 'running' ? Math.max(0, now - (r.activeSince ?? r.startedAt)) : 0)
}

export function onMeasure(
  s: Recap,
  e: { rateLimits: readonly { kind: string; percentUsed: number; resetsAt?: string }[]; costUsd?: number; at: number },
): Recap {
  const limits = { ...s.limits }
  for (const r of e.rateLimits) {
    const prev = limits[r.kind]
    const isNewWindow = prev === undefined || prev.resetsAt !== r.resetsAt || r.percentUsed < prev.percentUsed
    limits[r.kind] = {
      kind: r.kind,
      percentUsed: r.percentUsed,
      resetsAt: r.resetsAt,
      at: e.at,
      firstAt: isNewWindow ? e.at : prev.firstAt,
      firstPercent: isNewWindow ? r.percentUsed : prev.firstPercent,
    }
  }
  return { ...s, limits, costUsd: e.costUsd ?? s.costUsd }
}


/** Linear projection on the rate observed since the start of the session in this window. */
export function forecast(l: Limit): Forecast {
  const reset = l.resetsAt === undefined ? NaN : Date.parse(l.resetsAt)
  const elapsed = l.at - l.firstAt
  if (elapsed <= 0 || Number.isNaN(reset)) return { atReset: null, exhaustedAt: null }
  const rate = (l.percentUsed - l.firstPercent) / elapsed
  const atReset = Math.min(999, Math.round(l.percentUsed + rate * Math.max(0, reset - l.at)))
  const exhaustedAt = rate > 0 ? l.at + (100 - l.percentUsed) / rate : null
  return { atReset, exhaustedAt: exhaustedAt !== null && exhaustedAt < reset ? exhaustedAt : null }
}

/** Tokens that count toward the limits: cache reads are counted separately. */
export const weight = (t: Tokens): number => t.input + t.output + t.cacheWrite

export function totals(s: Recap): Tokens {
  return Object.values(s.buckets).reduce(
    (a, b) => ({
      input: a.input + b.tokens.input,
      output: a.output + b.tokens.output,
      cacheRead: a.cacheRead + b.tokens.cacheRead,
      cacheWrite: a.cacheWrite + b.tokens.cacheWrite,
    }),
    zero(),
  )
}


/** Alerts to raise now; `alerted` keeps those already raised. */
export function pendingAlerts(s: Recap, o: Options): Alert[] {
  const out: Alert[] = []
  for (const l of Object.values(s.limits)) {
    for (const [level, threshold] of [['critical', o.limitCritical], ['alert', o.limitWarn]] as const) {
      if (threshold > 0 && l.percentUsed >= threshold) {
        out.push({ key: `limit:${l.kind}:${threshold}:${l.resetsAt ?? ''}`, text: `${level}: limit ${limitLabel(l.kind)} at ${l.percentUsed}%` })
        break
      }
    }
  }
  for (const run of s.order.map(id => s.runs[id]!)) {
    if (o.agentTokenLimit > 0 && weight(run.tokens) >= o.agentTokenLimit) {
      out.push({ key: `agent:${run.id}`, text: `${run.agent} exceeded ${formatTokens(o.agentTokenLimit)} tokens` })
    }
    if (o.modelMismatch && run.spawnModel !== undefined && run.model !== run.spawnModel) {
      out.push({
        key: `model:${run.id}:${run.model}`,
        text: `${run.agent} answers on ${shortModel(run.model)} instead of ${shortModel(run.spawnModel)}`,
      })
    }
  }
  const total = weight(totals(s))
  if (o.sessionTokenLimit > 0 && total >= o.sessionTokenLimit) {
    out.push({ key: 'session', text: `the session exceeded ${formatTokens(o.sessionTokenLimit)} tokens` })
  }
  const main = s.runs[MAIN]
  if (o.mainShareLimit > 0 && main !== undefined && total >= MAIN_SHARE_FLOOR) {
    const share = Math.round((100 * weight(main.tokens)) / total)
    if (share > o.mainShareLimit) {
      out.push({ key: 'main-share', text: `the main agent (${main.agent}) makes up ${share}% of the session's tokens` })
    }
  }
  return out.filter(a => !s.alerted.includes(a.key))
}

export function markAlerted(s: Recap, alerts: readonly Alert[]): Recap {
  return alerts.length === 0 ? s : { ...s, alerted: [...s.alerted, ...alerts.map(a => a.key)].slice(-200) }
}

export function readOptions(raw: Readonly<Record<string, unknown>> | undefined): Options {
  const num = (k: keyof Options) => (typeof raw?.[k] === 'number' ? (raw[k] as number) : (DEFAULT_OPTIONS[k] as number))
  return {
    limitWarn: num('limitWarn'),
    limitCritical: num('limitCritical'),
    agentTokenLimit: num('agentTokenLimit'),
    sessionTokenLimit: num('sessionTokenLimit'),
    mainShareLimit: num('mainShareLimit'),
    modelMismatch: typeof raw?.modelMismatch === 'boolean' ? raw.modelMismatch : DEFAULT_OPTIONS.modelMismatch,
  }
}

// --- Display -------------------------------------------------------------------------------

/** `claude-xxx-5-5` → `xxx-5-5`, without the date suffix of a full id. */
export function shortModel(id: string): string {
  return id.replace(/^claude-/, '').replace(/-\d{8}$/, '')
}

export function formatTokens(n: number): string {
  if (n >= 1e6) return `${(n / 1e6).toFixed(1)}M`
  if (n >= 1e3) return `${(n / 1e3).toFixed(1)}k`
  return String(n)
}

export function limitLabel(kind: string): string {
  if (kind === 'five_hour') return '5 h'
  if (kind === 'seven_day') return '7 days'
  return kind.replace(/_/g, ' ')
}

export function bar(percent: number, width = 20): string {
  const filled = Math.max(0, Math.min(width, Math.round((percent / 100) * width)))
  return '█'.repeat(filled) + '░'.repeat(width - filled)
}

export const INSTANCE_LABEL: Record<Instance, string> = { new: 'new', resumed: 'resumed', fork: 'forked' }

export function sortedBuckets(s: Recap): Bucket[] {
  return Object.values(s.buckets).sort((a, b) => weight(b.tokens) - weight(a.tokens))
}

export function activeRuns(s: Recap): AgentRun[] {
  return s.order.map(id => s.runs[id]!).filter(r => r.id !== MAIN && r.status === 'running')
}

/** The children of an agent, in launch order. */
export function childrenOf(s: Recap, id: string): AgentRun[] {
  return s.order.map(i => s.runs[i]!).filter(r => r.parentId === id)
}

/** The peers of the main agent (CANON:17): launched by it, they still sit at its level. */
const PEER = /(^|:)(scribe|orchestrator)$/
export const isPeer = (agent: string): boolean => PEER.test(agent)

/**
 * The agents of the pane, in display order: the main agent and its peers (scribe, orchestrator) at level 0, whoever
 * launched them, every other agent under whoever launched it. A run whose parent is gone (dropped past MAX_RUNS)
 * comes back at level 0.
 */
export function agentTree(s: Recap): { run: AgentRun; depth: number }[] {
  const out: { run: AgentRun; depth: number }[] = []
  const seen = new Set<string>()
  const walk = (r: AgentRun, depth: number) => {
    if (seen.has(r.id)) return
    seen.add(r.id)
    out.push({ run: r, depth })
    for (const c of childrenOf(s, r.id)) if (!isPeer(c.agent)) walk(c, depth + 1)
  }
  const main = s.runs[MAIN]
  if (main !== undefined) walk(main, 0)
  for (const id of s.order) if (isPeer(s.runs[id]!.agent)) walk(s.runs[id]!, 0)
  for (const id of s.order) if (!seen.has(id)) walk(s.runs[id]!, 0)
  return out
}

/** Session usage per model × effort, all agents together, heaviest first. */
export function modelBuckets(s: Recap): Bucket[] {
  const out: Record<string, Bucket> = {}
  for (const b of Object.values(s.buckets)) {
    const key = `${b.model}\u0000${b.effort}`
    const cur = out[key] ?? { agent: '', model: b.model, effort: b.effort, tokens: zero(), calls: 0 }
    out[key] = {
      ...cur,
      tokens: {
        input: cur.tokens.input + b.tokens.input,
        output: cur.tokens.output + b.tokens.output,
        cacheRead: cur.tokens.cacheRead + b.tokens.cacheRead,
        cacheWrite: cur.tokens.cacheWrite + b.tokens.cacheWrite,
      },
      calls: cur.calls + b.calls,
    }
  }
  return Object.values(out).sort((a, b) => weight(b.tokens) - weight(a.tokens))
}


/** Current plan step (index), to attach the agents being launched. */
function runningStep(s: Recap): number | undefined {
  const i = s.plan?.steps.findIndex(x => x.status === 'running') ?? -1
  return i >= 0 ? i : undefined
}

function bumpStep(s: Recap, index: number, key: 'started' | 'finished'): Recap {
  const plan = s.plan
  if (plan === null || plan.steps[index] === undefined) return s
  const steps = plan.steps.map((x, i) => (i === index ? { ...x, [key]: x[key] + 1 } : x))
  return { ...s, plan: { ...plan, steps } }
}

// --- Step plan (declared by the orchestrator) ---------------------------------------------

const MAX_STEPS = 40
const STRIP_FOLD_MS = 5000

type StepInput = string | { name: string; agents?: number }
type StageInput = { name: string; steps: readonly StepInput[] }

const stepName = (x: StepInput): string => (typeof x === 'string' ? x : String(x.name))
const stepAgents = (x: StepInput): number =>
  typeof x === 'string' || !Number.isFinite(Number(x.agents)) ? 0 : Math.max(0, Math.min(50, Math.floor(Number(x.agents))))

/**
 * A plan sent back mid-way keeps the state of the steps already finished (matched by name).
 * `agents` per step = agent calls planned (a workflow knows their number): the bar
 * then advances at each finished agent, not only at each step.
 */
export function onPlan(
  s: Recap,
  e: { title?: string; steps?: readonly StepInput[]; stages?: readonly StageInput[]; isWorkflow?: boolean; at: number },
): Recap {
  const flat: { input: StepInput; stage: string }[] = []
  for (const st of e.stages ?? []) for (const n of st.steps) flat.push({ input: n, stage: String(st.name) })
  for (const n of e.steps ?? []) flat.push({ input: n, stage: '' })
  const old = new Map((s.plan?.steps ?? []).map(x => [x.name.toLowerCase(), x]))
  const steps: PlanStep[] = flat
    .map(x => ({ name: stepName(x.input).trim().slice(0, 80), stage: x.stage.trim().slice(0, 40), agents: stepAgents(x.input) }))
    .filter(x => x.name !== '')
    .slice(0, MAX_STEPS)
    .map(x => {
      const prev = old.get(x.name.toLowerCase())
      return prev?.status === 'done'
        ? { ...x, status: 'done' as const, doneAt: prev.doneAt, started: prev.started, finished: prev.finished }
        : { ...x, status: 'todo' as const, started: 0, finished: 0 }
    })
  if (steps.length === 0) return { ...s, plan: null }
  const first = steps.findIndex(x => x.status !== 'done')
  if (first >= 0) steps[first] = { ...steps[first]!, status: 'running' }
  const done = first < 0
  return {
    ...s,
    plan: {
      title: (e.title ?? s.plan?.title ?? '').slice(0, 60),
      isWorkflow: e.isWorkflow ?? s.plan?.isWorkflow ?? false,
      steps,
      state: done ? 'done' : 'running',
      note: '',
      startedAt: s.plan?.startedAt ?? e.at,
      endedAt: done ? e.at : undefined,
      ...stateShift(s.plan, done ? 'done' : 'running', e.at),
    },
  }
}

/** Duration of the fade from one state color to another. */
export const STATE_FADE_MS = 900
/** Transition fields when the state changes (nothing if the state is unchanged: the fade in progress carries on). */
function stateShift(plan: Plan | null | undefined, state: PlanState, at: number): { prevState?: PlanState; stateAt?: number } {
  if (plan === null || plan === undefined) return {}
  if (plan.state === state) return { prevState: plan.prevState, stateAt: plan.stateAt }
  return { prevState: plan.state, stateAt: at }
}
/** Is the color fade in progress? */
export const isFading = (plan: Plan | null, now: number): boolean => plan?.stateAt !== undefined && now - plan.stateAt < STATE_FADE_MS
/** State color, fading from the previous one for `STATE_FADE_MS` after a change. */
export function stateHex(plan: Plan, now?: number): string {
  const to = STATE_HEX[plan.state]
  if (now === undefined || plan.prevState === undefined || plan.stateAt === undefined) return to
  const t = Math.min(1, Math.max(0, (now - plan.stateAt) / STATE_FADE_MS))
  const ease = t * t * (3 - 2 * t)
  return mix(STATE_HEX[plan.prevState], to, ease)
}

/** `step`: number (starting at 1) or name. `done` moves on to the next step, which becomes running. */
export function onPlanStep(
  s: Recap,
  e: { step?: number | string; status?: 'running' | 'done' | 'failed'; state?: PlanState; note?: string; at: number },
): Recap {
  const plan = s.plan
  if (plan === null) return s
  let steps = plan.steps
  if (e.step !== undefined && e.status !== undefined) {
    const idx =
      typeof e.step === 'number'
        ? e.step - 1
        : plan.steps.findIndex(x => x.name.toLowerCase() === String(e.step).trim().toLowerCase())
    if (!Number.isInteger(idx) || idx < 0 || idx >= plan.steps.length) return s
    const status = e.status
    steps = plan.steps.map((x, i) =>
      i === idx ? { ...x, status, doneAt: status === 'done' ? e.at : x.doneAt } : x,
    )
    if (status === 'done') {
      for (let i = 0; i < idx; i++) {
        if (steps[i]!.status !== 'failed' && steps[i]!.status !== 'done') steps[i] = { ...steps[i]!, status: 'done', doneAt: e.at }
      }
      const next = steps[idx + 1]
      if (next !== undefined && next.status === 'todo') steps[idx + 1] = { ...next, status: 'running' }
    }
  }
  const finished = steps.every(x => x.status === 'done')
  const failed = steps.some(x => x.status === 'failed')
  const state: PlanState = finished ? 'done' : (e.state ?? (failed ? 'error' : e.status === 'done' || e.status === 'running' ? 'running' : plan.state))
  return {
    ...s,
    plan: {
      ...plan,
      steps,
      state,
      note: (e.note ?? (e.state !== undefined || e.step !== undefined ? '' : plan.note)).slice(0, 120),
      endedAt: finished ? (plan.endedAt ?? e.at) : undefined,
      ...stateShift(plan, state, e.at),
    },
  }
}

export function planProgress(plan: Plan): {
  done: number
  total: number
  percent: number
  current: PlanStep | undefined
  index: number
  stage: string
  agentsDone: number
  agentsPlanned: number
} {
  const total = plan.steps.length
  const done = plan.steps.filter(x => x.status === 'done').length
  const index = plan.steps.findIndex(x => x.status === 'running' || x.status === 'failed')
  const current = index >= 0 ? plan.steps[index] : undefined
  // Current step with planned agents: fraction of agents finished, capped at 90% (the rest is the verification).
  const fraction = (x: PlanStep): number =>
    x.status === 'done' ? 1 : x.status === 'running' && x.agents > 0 ? Math.min(0.9, x.finished / x.agents) : 0
  const sum = plan.steps.reduce((n, x) => n + fraction(x), 0)
  return {
    done,
    total,
    percent: total === 0 ? 0 : Math.round((sum / total) * 100),
    current,
    index: index + 1,
    stage: current?.stage ?? '',
    agentsDone: plan.steps.reduce((n, x) => n + x.finished, 0),
    agentsPlanned: plan.steps.reduce((n, x) => n + x.agents, 0),
  }
}

export type WorkflowStage = {
  name: string
  planned: number // planned agents (sum of the steps)
  runs: AgentRun[] // agents already launched in this phase, from oldest to newest
  placeholders: number // planned agents not launched yet
  done: number // agents finished
  status: PlanStep['status']
}
/** Phases of a workflow (consecutive steps of the same phase) with their agents, launched or upcoming. */
export function workflowStages(s: Recap): WorkflowStage[] {
  const plan = s.plan
  if (plan === null || !plan.isWorkflow) return []
  const groups: { name: string; idx: number[] }[] = []
  plan.steps.forEach((x, i) => {
    const last = groups[groups.length - 1]
    if (last !== undefined && last.name === x.stage) last.idx.push(i)
    else groups.push({ name: x.stage, idx: [i] })
  })
  const running = groups.findIndex(g => g.idx.some(i => plan.steps[i]!.status === 'running'))
  const fallback = running >= 0 ? running : groups.length - 1
  return groups.map(g => {
    const steps = g.idx.map(i => plan.steps[i]!)
    // an agent launched before the plan (without a step) is attached to the current phase
    const runs = s.order
      .map(id => s.runs[id]!)
      .filter(r => r.id !== MAIN && (r.stepIndex !== undefined ? g.idx.includes(r.stepIndex) : groups.indexOf(g) === fallback))
    const planned = steps.reduce((n, x) => n + x.agents, 0)
    return {
      name: g.name !== '' ? g.name : plan.title,
      planned,
      runs,
      placeholders: Math.max(0, planned - runs.length),
      done: steps.reduce((n, x) => n + x.finished, 0),
      status: steps.every(x => x.status === 'done') ? 'done' : steps.some(x => x.status === 'failed') ? 'failed' : steps.some(x => x.status === 'running') ? 'running' : 'todo',
    }
  })
}

export const isPlanLive = (s: Recap): boolean => s.plan !== null && s.plan.endedAt === undefined

/** Last tool called by an agent (`tool.call` carries the agentId; absent = main agent). */
export function onToolUse(s: Recap, e: { agentId?: string; tool: string }): Recap {
  const id = e.agentId ?? MAIN
  const run = s.runs[id]
  if (run === undefined || run.tool === e.tool) return s
  return withRun(s, { ...run, tool: e.tool.replace(/^mcp__/, '') })
}

/** Sub-agents to show under the bar: active, failed, or finished less than 5 s ago. */
export function stripRuns(s: Recap, now: number): AgentRun[] {
  return s.order
    .map(id => s.runs[id]!)
    .filter(
      r =>
        r.id !== MAIN &&
        (r.status === 'running' || r.status === 'failed' || (r.endedAt !== undefined && now - r.endedAt < STRIP_FOLD_MS)),
    )
}

/** `42s`, `1 min 05`, `1 h 02`. */
export function duration(ms: number): string {
  const sec = Math.max(0, Math.floor(ms / 1000))
  if (sec < 60) return `${sec}s`
  const m = Math.floor(sec / 60)
  if (m < 60) return `${m} min ${String(sec % 60).padStart(2, '0')}`
  return `${Math.floor(m / 60)} h ${String(m % 60).padStart(2, '0')}`
}

/** Animated bar: a glint runs across the filled part (`frame` = tick counter). */
export function shimmerBar(percent: number, width: number, frame: number, isLive: boolean): string {
  const filled = Math.max(0, Math.min(width, Math.round((percent / 100) * width)))
  const cells: string[] = []
  const spot = filled > 0 ? frame % filled : -1
  for (let i = 0; i < width; i++) {
    if (i >= filled) cells.push('░')
    else cells.push(isLive && (i === spot || i === spot - 1) ? '▓' : '█')
  }
  return cells.join('')
}

export const SPINNER = ['⠋', '⠙', '⠹', '⠸', '⠼', '⠴', '⠦', '⠧', '⠇', '⠏']

/** Aligned table: columns separated by two spaces, numbers on the right. */
export function table(rows: readonly (readonly string[])[], rightFrom = 1): string[] {
  const w: number[] = []
  for (const r of rows) r.forEach((c, i) => (w[i] = Math.max(w[i] ?? 0, c.length)))
  return rows.map(r => r.map((c, i) => (i >= rightFrom ? c.padStart(w[i]!) : c.padEnd(w[i]!))).join('  '))
}


// --- Drawn bar (desktop: SVG; terminal: colored cells) ----------------------------

export const STATE_HEX = { running: '#8b5cf6', input: '#f59e0b', error: '#ef4444', done: '#22c55e' } as const

const esc = (t: string): string => t.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

// Lattice like a contribution grid: 2×2 px cells on a 4 px pitch, 5 rows, 1 px margin.
// Each cell carries a soft halo over its 4×4 tile (edges at ~½, corners at ~¼ of its intensity):
// the gaps between cells are tinted and the checkerboard reads almost continuous.
const SQ = 2 // side of a cell, in px
const GAP = 2
const ROWS = 5
const INSET = 1 // offset of the cells from the top and left edges of the track
const TRACK_Y = 4
const TRACK_H = 20
const BADGE_H = 24
const EDGE = 0.54 // halo edge intensity, relative to the cell core
const CORNER = 0.27 // halo corner intensity
/** Alpha profile of the core of an average cell (t: 0 at the start, 1 against the badge): rising from left to right. */
const FADE: [number, number][] = [
  [0, 0.012],
  [0.06, 0.02],
  [0.14, 0.037],
  [0.2, 0.05],
  [0.3, 0.085],
  [0.38, 0.115],
  [0.45, 0.18],
  [0.53, 0.23],
  [0.69, 0.38],
  [0.78, 0.41],
  [1, 0.43],
]
/** Noise levels (intensity multipliers); the last one is the spark, whiter. */
const NOISE = [0.85, 1, 1.35, 1.65]
const SPARK = NOISE.length - 1
/** Alpha added to the sparks (zero against the badge, where the fade is enough): they stay readable in the faded start of the bar. */
const SPARK_MIN = 0.09
const NCOLS = 37 // table period, prime so that the repetition does not show
/** Fixed 5 × 37 table of levels (fixed seed): ~8% sparks, spread over the whole length, never two neighbours (diagonals included). */
const NOISE_TABLE: number[][] = (() => {
  let seed = 324 // chosen so that every window of 4 columns holds at least one spark
  const rnd = () => ((seed = (seed * 1103515245 + 12345) & 0x7fffffff), (seed >> 8) / 0x7fffff)
  const rows: number[][] = []
  for (let row = 0; row < ROWS; row++) {
    const line: number[] = []
    for (let c = 0; c < NCOLS; c++) {
      const r = rnd()
      let v = r < 0.12 ? 0 : r < 0.55 ? 1 : r < 0.93 ? 2 : SPARK
      const near = [line[c - 1], rows[row - 1]?.[c - 1], rows[row - 1]?.[c], rows[row - 1]?.[(c + 1) % NCOLS], c === NCOLS - 1 ? line[0] : -1]
      if (v === SPARK && near.includes(SPARK)) v = 2
      line.push(v)
    }
    rows.push(line)
  }
  return rows
})()
// Fixed terminal intensities (progressCells): a period of 14 columns, 6 intensities.
const COLS = 14
const LEVELS = [0.3, 0.45, 0.6, 0.75, 0.9, 1]
/** Fixed intensities (fixed seed), with no two equal neighbours horizontally or vertically. */
const PATTERN: number[][] = (() => {
  let seed = 7
  const rows: number[][] = []
  for (let row = 0; row < ROWS; row++) {
    const line: number[] = []
    for (let c = 0; c < COLS; c++) {
      let v = 0
      do {
        seed = (seed * 1103515245 + 12345) & 0x7fffffff
        v = (seed >> 16) % LEVELS.length
      } while (v === line[c - 1] || v === rows[row - 1]?.[c] || (c === COLS - 1 && v === line[0]))
      line.push(v)
    }
    rows.push(line)
  }
  return rows
})()
const level = (c: number, row: number): number => LEVELS[PATTERN[row % ROWS]![((c % COLS) + COLS) % COLS]!]!
/** Width in px of a text column, to convert `bodyColumns` to pixels. */
const COL_PX = 7
/** Bar width: the available line (minus a margin and the `reserved` columns of what shares it), from 160 px to 1600 px. */
export const barWidth = (bodyColumns: number, reserved = 0): number =>
  Math.min(1600, Math.max(160, Math.floor((bodyColumns - 4 - reserved) * COL_PX)))
/** Height in px of the SVG bar (the badge overflows the track). */
export const PROGRESS_HEIGHT = TRACK_H + TRACK_Y * 2
/** Width in px of the SVG bar for a requested width. */
export const progressWidth = (width: number): number => Math.max(120, Math.floor(width))
/**
 * Root style of the desktop SVGs, transparent background. The SVGs are drawn as images, never in an isolated frame
 * (`isInteractive`): the frame, recreated at each band render, flashed white and restarted the animations.
 */
const SVG_ROOT_STYLE = 'color-scheme:light dark;background:transparent'
/** Width of an agent card depending on the room: 1, 2 or 3 per row. */
export const cardWidth = (bodyColumns: number): '100%' | '50%' | '33%' => (bodyColumns < 64 ? '100%' : bodyColumns < 104 ? '50%' : '33%')
/** Gap between two agent cards, in cells: one column to the right of each card, one row between two rows of cards. */
export const CARD_GAP = 1

/**
 * SVG bar: pill-shaped track, the fill is a fixed 5-row lattice of 2×2 cells laid on a tinted bed
 * in a light version of the state color. A static fade goes from the minimum on the left (start)
 * to full on the right (against the badge), a few fixed cells sparkle; while the plan runs, a wave of
 * lighter or darker colors starts against the badge and recedes to the left (SMIL), fading with the fade.
 * The cells never move, only the color does.
 * No tick marks. One zone per step with a `<title>` (tooltip, only where the SVG is interactive). The phase badge
 * is solid, stuck to the front of the fill, which stops sharply at its left edge (nothing under it or in its corners).
 * `uid` suffixes the ids when several bars share one document (test page).
 */
export function progressSvg(plan: Plan, width: number, now: number, uid = ''): string {
  const p = planProgress(plan)
  const pitch = SQ + GAP
  const H = PROGRESS_HEIGHT // 28, the badge (24 px) overflows the track
  const R = TRACK_H / 2 // rounding of the track and of the fill: pill
  const W = progressWidth(width)
  const live = plan.endedAt === undefined && plan.state === 'running'
  // final colors in the markup; the state fade is a CSS animation applied while it lasts, so that
  // the source stays identical from one tick to the next (the desktop isolated frame reloads at each source change)
  const hex = STATE_HEX[plan.state]
  const fading = plan.prevState !== undefined && plan.prevState !== plan.state && isFading(plan, now)
  const prevHex = plan.prevState !== undefined ? STATE_HEX[plan.prevState] : hex
  const n = plan.steps.length
  // badge: computed first, the fade stops at its left edge
  const label = p.stage.length > 12 ? `${p.stage.slice(0, 11)}…` : p.stage
  // shown as soon as a phase is running, even at 0% (it then covers the start of the track)
  const hasBadge = p.stage !== ''
  const pw = hasBadge ? Math.ceil(label.length * 7 + 22) : 0
  const ph = BADGE_H
  // the badge sits at the start of the track and hides the start of the fill: at 0% the front is in the middle of the badge
  const px = 0
  const half = pw / 2
  const fillW = Math.round(half + ((W - half) * p.percent) / 100)
  // the fill stops sharply at the badge's left edge (x = px): nothing passes under it, so no
  // cell shows in its rounded corners (the track shows there, as around the rest of the badge)
  const cy = TRACK_Y + TRACK_H / 2
  const clipW = fillW
  const fadeStart = hasBadge ? half : 0
  const fadeEnd = Math.max(fadeStart + 1, fillW)
  // fixed cells grouped by noise level, each in three layers (4×4 tile, cross, 2×2 core)
  // whose composed opacities give corners / edges / core in the proportions CORNER / EDGE / 1;
  // the tiles rest on a continuous bed (the lowest level) and are merged in runs
  // of the same level, so that no seam shows at high zoom
  const cols = Math.ceil(clipW / pitch) + NCOLS
  const tiles = NOISE.map(() => ['', '', ''])
  for (let row = 0; row < ROWS; row++) {
    const y = TRACK_Y + row * pitch
    for (let c = 0; c < cols; c++) {
      const x = c * pitch
      const k = NOISE_TABLE[row]![c % NCOLS]!
      const t = tiles[k]!
      let run = 1
      while (c + run < cols && NOISE_TABLE[row]![(c + run) % NCOLS] === k) run++
      t[0] += `M${x} ${y}h${pitch * run}v4h-${pitch * run}z`
      for (let j = 0; j < run; j++) {
        const xj = x + j * pitch
        t[1] += `M${xj + 1} ${y}h2v1h1v2h-1v1h-2v-1h-1v-2h1z`
        t[2] += `M${xj + INSET} ${y + INSET}h${SQ}v${SQ}h-${SQ}z`
      }
      c += run - 1
    }
  }
  const light = mix(hex, '#ffffff', 0.55)
  const sparkHex = mix(hex, '#ffffff', 0.7)
  const paint = light
  const top = NOISE[SPARK]!
  const meanNoise = NOISE_TABLE.flat().reduce((m, v) => m + NOISE[v]!, 0) / (ROWS * NCOLS)
  const op = (v: number) => +v.toFixed(3)
  const bedA = (CORNER * NOISE[0]!) / top // continuous bed: the tile of the lowest level
  const layers = (k: number, fill: string) => {
    const [sq, plus, core] = tiles[k]!
    if (!core) return ''
    const cc = NOISE[k]! / top
    const sA = CORNER * cc
    const extra = k === 0 && fill === paint ? 0 : 1 - (1 - sA) / (1 - (fill === paint ? bedA : 0))
    const pA = 1 - (1 - EDGE * cc) / (1 - sA)
    const qA = 1 - (1 - cc) / (1 - EDGE * cc)
    return (
      (extra > 0 ? `<path d="${sq}" fill="${fill}" fill-opacity="${op(extra)}"/>` : '') +
      `<path d="${plus}" fill="${fill}" fill-opacity="${op(pA)}"/>` +
      `<path d="${core}" fill="${fill}" fill-opacity="${op(qA)}"/>`
    )
  }
  const bedPath = `M0 ${TRACK_Y}h${cols * pitch}v${TRACK_H}h-${cols * pitch}z`
  const tilesSpark = tiles[SPARK]![0]
  // the bed does not pass under the sparks (they have their own color and their own fade)
  const cellPaths =
    `<path d="${bedPath}${tilesSpark ? ` ${tilesSpark}` : ''}" fill-rule="evenodd" fill="${paint}" fill-opacity="${op(bedA)}"/>` +
    NOISE.map((_, k) => (k === SPARK ? '' : layers(k, paint))).join('')
  const sparkPaths = layers(SPARK, sparkHex)
  const stops = FADE.map(([t, a]) => `<stop offset="${t}" stop-color="#fff" stop-opacity="${op((a * top) / meanNoise)}"/>`).join('')
  const sparkStops = FADE.map(
    ([t, a]) => `<stop offset="${t}" stop-color="#fff" stop-opacity="${op(Math.min(1, (a * top) / meanNoise + SPARK_MIN * Math.min(1, Math.max(0, (0.85 - t) / 0.3))))}"/>`,
  ).join('')
  // fill shape: pill on the left, straight right edge against the badge (cap only if very short)
  const fillShape = `<rect x="0" y="${TRACK_Y}" width="${clipW}" height="${TRACK_H}" rx="${R}"/>`
  const parts: string[] = []
  parts.push(`<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" style="${SVG_ROOT_STYLE}">`)
  if (fading) {
    const fade = (name: string, from: string, to: string) =>
      `@keyframes ${name}${uid}{from{fill:${from}}}[fill="${to}"]{animation:${name}${uid} ${STATE_FADE_MS}ms ease-in-out both}`
    // the badge (hex) and the cells (light, sparkHex) have distinct tints: one selector per tint
    parts.push(`<style>${fade('h', prevHex, hex)}${fade('l', mix(prevHex, '#ffffff', 0.55), light)}${fade('s', mix(prevHex, '#ffffff', 0.7), sparkHex)}</style>`)
  }
  parts.push(
    `<defs><clipPath id="c${uid}">${fillShape}</clipPath>` +
      // static fade: minimum on the left (start), full on the right against the badge; the wave is born there and fades as it recedes
      `<linearGradient id="f${uid}" gradientUnits="userSpaceOnUse" x1="${fadeStart}" y1="0" x2="${fadeEnd}" y2="0">${stops}</linearGradient>` +
      `<mask id="m${uid}"><rect x="0" y="0" width="${Math.max(1, Math.ceil(clipW))}" height="${H}" fill="url(#f${uid})"/></mask>` +
      (sparkPaths
        ? `<linearGradient id="s${uid}" gradientUnits="userSpaceOnUse" x1="${fadeStart}" y1="0" x2="${fadeEnd}" y2="0">${sparkStops}</linearGradient>` +
          `<mask id="k${uid}"><rect x="0" y="0" width="${Math.max(1, Math.ceil(clipW))}" height="${H}" fill="url(#s${uid})"/></mask>`
        : '') +
      `</defs>`,
  )
  // neutral, slightly warm grey track: on a bluish card background, it does not cool the start of the fill
  parts.push(`<rect x="0" y="${TRACK_Y}" width="${W}" height="${TRACK_H}" rx="${R}" fill="#8a8a87" fill-opacity="0.2"/>`)
  // the translation moves the lattice to the left to give the impression that the cells change color
  const values = Array.from({ length: NCOLS + 1 }, (_, i) => `${-i * pitch} 0`).join('; ')
  // still outside `running` (waiting, error, done)
  const anim = live ? `<animateTransform attributeName="transform" type="translate" values="${values}" dur="4s" repeatCount="indefinite" calcMode="discrete"/>` : ''
  if (clipW > 0) parts.push(`<g clip-path="url(#c${uid})"><g mask="url(#m${uid})"><g>${anim}${cellPaths}</g></g>${sparkPaths ? `<g mask="url(#k${uid})"><g>${anim}${sparkPaths}</g></g>` : ''}</g>`)
  plan.steps.forEach((x, i) => {
    const x0 = Math.round((i / n) * W)
    const x1 = Math.round(((i + 1) / n) * W)
    const t =
      x.status === 'done'
        ? `✓ ${x.name}${x.doneAt !== undefined ? ` · ${duration(x.doneAt - plan.startedAt)}` : ''}`
        : `${x.status === 'running' ? '● ' : ''}${x.name}`
    parts.push(`<rect x="${x0}" y="0" width="${x1 - x0}" height="${H}" fill="#0000"><title>${esc(t)}</title></rect>`)
  })
  if (hasBadge) {
    const py = (H - ph) / 2
    const [br, bg, bb] = rgb(hex)
    const textColor = br * 0.299 + bg * 0.587 + bb * 0.114 > 130 ? '#16161a' : '#ffffff'
    parts.push(
      `<rect x="${px}" y="${py}" width="${pw}" height="${ph}" rx="${ph / 2}" fill="${hex}"/>` +
        `<text x="${px + pw / 2}" y="${py + ph / 2 + 4.2}" font-size="12" font-weight="700" fill="${textColor}" text-anchor="middle" font-family="system-ui,sans-serif">${esc(label)}<title>${esc(plan.endedAt !== undefined ? `${plan.title || 'plan'} · ${duration(plan.endedAt - plan.startedAt)}` : plan.title || 'plan')}</title></text>`,
    )
  }
  parts.push('</svg>')
  return parts.join('')
}

const lerp = (a: number, b: number, t: number): number => Math.round(a + (b - a) * t)
/** Mixes `hex` toward `target` (0 = hex, 1 = target), as `#rrggbb`. */
function mix(hex: string, target: string, t: number): string {
  const a = rgb(hex)
  const b = rgb(target)
  return `#${[0, 1, 2].map(i => lerp(a[i]!, b[i]!, t).toString(16).padStart(2, '0')).join('')}`
}
const rgb = (hex: string): [number, number, number] => [
  parseInt(hex.slice(1, 3), 16),
  parseInt(hex.slice(3, 5), 16),
  parseInt(hex.slice(5, 7), 16),
]

// Braille: one character = 2 columns × 4 rows of dots; bits per (column, row).
const BRAILLE_BITS = [
  [0x01, 0x02, 0x04, 0x40],
  [0x08, 0x10, 0x20, 0x80],
] as const
export const BRAILLE_TRACK = 0x2800 + 0xc0 // ⣀: the track, two dots at the bottom

/**
 * Terminal cells for `Raster`: words `[code point, foreground, background]`, little-endian
 * u32. Each cell is a braille character: a grid of dots of varying intensities that recede by
 * half a cell per frame and fade toward the back.
 */
export function progressCells(plan: Plan, columns: number, frame: number, now?: number): Uint32Array {
  const p = planProgress(plan)
  const filled = Math.round((columns * p.percent) / 100)
  const live = plan.endedAt === undefined && plan.state === 'running'
  const [r, g, b] = rgb(stateHex(plan, now))
  const shift = live ? frame : 0
  const words = new Uint32Array(columns * 3)
  for (let i = 0; i < columns; i++) {
    let ch = BRAILLE_TRACK
    let fg = 0x555566
    if (i < filled) {
      const fade = filled <= 1 ? 1 : 0.12 + 0.88 * (i / (filled - 1)) // 0.12 at the back → 1 at the front
      let bits = 0
      for (let sc = 0; sc < 2; sc++) {
        for (let row = 0; row < 4; row++) {
          const norm = (level(2 * i + sc + shift, row) - LEVELS[0]!) / (1 - LEVELS[0]!) // 0 → 1
          if (norm <= fade) bits |= BRAILLE_BITS[sc]![row]!
        }
      }
      ch = 0x2800 + (bits === 0 ? 0x40 : bits)
      const c = (v: number) => lerp(0x30, v, 0.35 + 0.65 * fade)
      fg = (c(r) << 16) | (c(g) << 8) | c(b)
    }
    words[i * 3] = ch
    words[i * 3 + 1] = fg
    words[i * 3 + 2] = 0x01000000
  }
  return words
}

// --- Mascot (SVG pixel art) -----------------------------------------------------------------

/** Default height and width in px of the mascot (13 × 12.5 grid). */
export const CRAB_HEIGHT = 30
export const crabWidth = (h = CRAB_HEIGHT): number => Math.round((h * 13) / 12.5)

export type Tier = 'haiku' | 'sonnet' | 'opus' | 'fable'
/** Tier of a model from its id; unknown: the simplest. */
export function tierOf(id: string): Tier {
  const m = /haiku|sonnet|opus|fable/i.exec(id)
  return (m?.[0].toLowerCase() as Tier | undefined) ?? 'haiku'
}

/**
 * Named mascots. An agent picks its own with the `mascot` field of its frontmatter (next to `model` and
 * `effort`, which Claude Code ignores); without the field, it wears the trade of its model.
 */
export const MASCOTS = ['scribe', 'chef', 'artist', 'inspector', 'courier', 'artisan', 'scholar', 'mage', 'bare'] as const
export type Mascot = (typeof MASCOTS)[number]
const TIER_MASCOT: Record<Tier, Mascot> = { haiku: 'courier', sonnet: 'artisan', opus: 'scholar', fable: 'mage' }
/** One emoji per mascot for the terminal. */
export const MASCOT_EMOJI: Record<Mascot, string> = {
  scribe: '📜', chef: '🧠', artist: '🎨', inspector: '🔍', courier: '📦', artisan: '🔨', scholar: '🎓', mage: '🔮', bare: '◦',
}
export const isMascot = (v: unknown): v is Mascot => typeof v === 'string' && (MASCOTS as readonly string[]).includes(v)
/** The mascot of an agent: that of its definition, otherwise the trade of its model. */
export function mascotOf(r: { mascot?: string; model: string }): Mascot {
  return isMascot(r.mascot) ? r.mascot : TIER_MASCOT[tierOf(r.model)]
}

/** `name` and `mascot` from the frontmatter of an agent definition (`.md` file), without relying on a YAML parser. */
export function agentFront(text: string): { name?: string; mascot?: Mascot } {
  const m = /^---\r?\n([\s\S]*?)\r?\n---/.exec(text)
  if (m === null) return {}
  const field = (k: string) => new RegExp(`^${k}:[ \\t]*["']?([^"'#\\r\\n]*?)["']?[ \\t]*(?:#.*)?$`, 'm').exec(m[1]!)?.[1]
  const name = field('name') || undefined
  const mascot = field('mascot')
  return { name, mascot: isMascot(mascot) ? mascot : undefined }
}

/** `installPath` of each installed plugin, by plugin name, read from `plugins/installed_plugins.json`. */
export function installPathsOf(json: string): Record<string, string> {
  const out: Record<string, string> = {}
  try {
    const plugins = (JSON.parse(json) as { plugins?: Record<string, unknown> }).plugins ?? {}
    for (const [key, v] of Object.entries(plugins)) {
      const entries = (Array.isArray(v) ? v : [v]) as { installPath?: unknown }[]
      const path = entries.find(x => typeof x?.installPath === 'string')?.installPath
      if (typeof path === 'string') out[key.split('@')[0]!] ??= path
    }
  } catch {
    // file missing or in another format: fall back to the other locations
  }
  return out
}

/**
 * Folders where to look for the definition of an agent type, and the `name` to find there. `plugin:name`: the
 * `agents/` folder of the installed plugin, then that of a sibling plugin of the Mod (marketplace repo, `--plugin-dir`);
 * `name` alone: the project's agents, then the user's. Built-in types have no file.
 */
export function agentDirs(
  type: string,
  ctx: { pluginRoot: string; configDir?: string; sessionRoot?: string; installPaths?: Record<string, string> },
): { dir: string; name: string }[] {
  const cut = type.indexOf(':')
  if (cut > 0) {
    const plugin = type.slice(0, cut)
    const name = type.slice(cut + 1)
    const dirs = [ctx.installPaths?.[plugin], `${ctx.pluginRoot.replace(/\/+$/, '').replace(/\/[^/]+$/, '')}/${plugin}`]
    return dirs.filter((d): d is string => d !== undefined).map(d => ({ dir: `${d}/agents`, name }))
  }
  return [ctx.sessionRoot && `${ctx.sessionRoot}/.claude/agents`, ctx.configDir && `${ctx.configDir}/agents`]
    .filter((d): d is string => typeof d === 'string' && d !== '')
    .map(dir => ({ dir, name: type }))
}

/** The Claude Code configuration folder, derived from the folder of an installed plugin (`…/plugins/cache/…`). */
export function configDirOf(pluginRoot: string): string | undefined {
  const at = pluginRoot.indexOf('/plugins/cache/')
  return at > 0 ? pluginRoot.slice(0, at) : undefined
}

/** Records the mascot read from an agent's definition. */
export function onMascot(s: Recap, e: { agentId: string; mascot: Mascot }): Recap {
  const run = s.runs[e.agentId]
  return run === undefined || run.mascot === e.mascot ? s : withRun(s, { ...run, mascot: e.mascot })
}

/** Grey of the same luminance: the mascot of an inactive agent, accessories included. */
function grey(hex: string): string {
  const n = parseInt(hex.slice(1), 16)
  const l = Math.round(0.3 * (n >> 16) + 0.59 * ((n >> 8) & 255) + 0.11 * (n & 255))
  const v = l.toString(16).padStart(2, '0')
  return `#${v}${v}${v}`
}

/**
 * Claude Code mascot in pixel art, 13 × 12 grid (shown on two lines): body, arms, eyes, four
 * legs at the bottom, dressed according to `mascot` — scribe: hood, quill and scroll; chef: toque with a brain badge,
 * white jacket with sleeves, scarf, wooden spoon; artist: beret, palette, brush, paint splashes;
 * inspector: detective cap, magnifying glass, smoking pipe (for a test or debugging agent);
 * courier: cap, parcel, hurried stride; artisan: bandana, tool belt, hammer; scholar: mortarboard,
 * glasses, bow tie, diploma; mage: starred hat, gem staff, sparks. Without `mascot`, the trade
 * of the `tier` model; with neither, the bare mascot (future slot).
 */
export function crabSvg(o: { height?: number; body?: string; eye?: string; animated?: boolean; tier?: Tier; mascot?: Mascot; mono?: boolean } = {}): string {
  const h = o.height ?? CRAB_HEIGHT
  const mono = o.mono === true // inactive: black and white, accessories included
  const c = (hex: string) => (mono ? grey(hex) : hex)
  const body = mono ? '#9a9a9a' : (o.body ?? '#d97757')
  const eye = c(o.eye ?? '#1b1b1f')
  const OY = 5 // the body occupies rows 5 to 11, hats and props rows 0 to 6
  const px = (x: number, y: number, w = 1, hh = 1, fill = body) => `<rect x="${x}" y="${y}" width="${w}" height="${hh}" fill="${fill}"/>`
  const parts = [
    px(2, OY, 9, 5), // body
    px(0, OY + 2, 2, 2), // left arm
    px(11, OY + 2, 2, 2), // right arm
    px(3, OY + 5, 1, 2),
    px(5, OY + 5, 1, 2),
    px(7, OY + 5, 1, 2),
    px(9, OY + 5, 1, 2), // legs
  ]
  const eyes = () => parts.push(px(4, OY + 1, 1, 2, eye), px(8, OY + 1, 1, 2, eye))
  const white = c('#f4f4f4')
  const gold = c('#f5c542')
  const red = c('#d83a3a')
  const wood = c('#8b5a2b')
  const design: Mascot = o.mascot ?? (o.tier !== undefined ? TIER_MASCOT[o.tier] : 'bare')
  switch (design) {
    case 'scribe': {
      // scribe's hood, quill in the right claw, rolled parchment in the left claw
      const hood = c('#6b4a2b')
      parts.push(px(4, 2, 5, 1, hood), px(3, 3, 7, 1, hood), px(2, 4, 9, 1, c('#8a6240')))
      parts.push(px(12, 0, 1, 1, white), px(11, 1, 2, 2, white), px(12, 1, 1, 2, c('#cfcfcf')), px(11, 3, 1, 1, white), px(11, 4, 1, 2, c('#3a3a3a')), px(11, 6, 1, 1, c('#2b4fc7')))
      const roll = c('#c9a86a')
      parts.push(px(0, 2, 2, 4, c('#f3e3b5')), px(0, 1, 2, 1, roll), px(0, 6, 2, 1, roll), px(0, 3, 1, 1, c('#6b4a2b')), px(1, 4, 1, 1, c('#6b4a2b')))
      eyes()
      break
    }
    case 'chef': {
      // the head chef: toque with a brain badge, white jacket with sleeves, pointed red scarf, raised wooden spoon
      const toque = c('#f7f7f7')
      parts.push(px(4, 0, 5, 1, toque), px(3, 1, 7, 1, toque), px(4, 2, 5, 2, toque), px(3, 4, 7, 1, c('#dcdcdc')))
      parts.push(px(5, 2, 3, 2, c('#f08bb0')), px(6, 2, 1, 2, c('#c9567f')))
      parts.push(px(2, OY + 3, 9, 2, toque), px(0, OY + 2, 2, 2, toque), px(11, OY + 2, 2, 2, toque)) // jacket and sleeves
      parts.push(px(5, OY + 3, 3, 1, red), px(6, OY + 4, 1, 1, red), px(4, OY + 4, 1, 1, c('#bdbdbd')), px(8, OY + 4, 1, 1, c('#bdbdbd'))) // scarf, buttons
      parts.push(px(11, 0, 2, 2, c('#b07a43')), px(12, 2, 1, 5, wood))
      eyes()
      break
    }
    case 'artist': {
      // red beret askew, palette in the left claw, brush dipped in the right one, paint splashes
      const beret = c('#c0392b')
      parts.push(px(8, 2, 1, 1, beret), px(3, 3, 7, 1, beret), px(2, 4, 7, 1, beret))
      parts.push(px(0, 3, 2, 3, c('#c8a26b')), px(0, 3, 1, 1, c('#e74c3c')), px(1, 4, 1, 1, c('#2f7de1')), px(0, 5, 1, 1, c('#f5c542')))
      parts.push(px(12, 0, 1, 1, c('#2f7de1')), px(12, 1, 1, 1, c('#9aa3ad')), px(12, 2, 1, 5, c('#26262b')))
      parts.push(px(3, OY + 4, 1, 1, c('#2f7de1')), px(9, OY + 3, 1, 1, c('#f5c542')))
      eyes()
      break
    }
    case 'inspector': {
      // tweed detective cap and its knot, magnifying glass in the right claw, smoking pipe in the left one
      const tweed = c('#8a6a3f')
      const check = c('#6b5130')
      parts.push(px(6, 1, 1, 1, check), px(4, 2, 5, 1, tweed), px(3, 3, 7, 1, tweed), px(2, 4, 9, 1, tweed))
      parts.push(px(5, 2, 1, 1, check), px(7, 2, 1, 1, check), px(4, 3, 1, 1, check), px(6, 3, 1, 1, check), px(8, 3, 1, 1, check), px(3, 4, 1, 1, check), px(9, 4, 1, 1, check))
      const rim = c('#26262b')
      parts.push(px(11, 0, 2, 1, rim), px(11, 1, 2, 2, c('#cfe8ff')), px(11, 3, 2, 1, rim), px(12, 4, 1, 3, wood))
      parts.push(px(0, 4, 1, 2, c('#5a3a1a')), px(1, 6, 1, 1, c('#3a2a1a')), px(0, 2, 1, 1, c('#bdbdbd')), px(1, 1, 1, 1, c('#d9d9d9')))
      eyes()
      break
    }
    case 'courier': {
      // the courier: cap seen from the front (crown, logo, peak), parcel in the right claw
      const cap = c('#2f7de1')
      parts.push(px(4, 2, 5, 1, cap), px(3, 3, 7, 1, cap), px(6, 3, 1, 1, white), px(1, 4, 11, 1, c('#1f5fb3')))
      parts.push(px(11, 5, 2, 2, c('#c08a4a')), px(11, 5, 1, 2, c('#e8c48a')))
      eyes()
      break
    }
    case 'artisan': {
      // the artisan: polka-dot bandana, tool belt and its buckle, hammer in the right claw
      parts.push(px(2, 4, 9, 1, red), px(4, 4, 1, 1, white), px(8, 4, 1, 1, white))
      parts.push(px(2, OY + 4, 9, 1, c('#7a4a2a')), px(6, OY + 4, 1, 1, gold), px(3, OY + 4, 1, 1, c('#9aa3ad')), px(9, OY + 4, 1, 1, c('#9aa3ad')))
      parts.push(px(10, 2, 3, 1, c('#9aa3ad')), px(12, 3, 1, 4, wood))
      eyes()
      break
    }
    case 'scholar': {
      // the scholar: mortarboard with gold tassel, glasses, bow tie, diploma in the right claw
      const ink = c('#26262b')
      parts.push(px(3, 2, 7, 1, ink), px(1, 3, 11, 1, ink), px(4, 4, 5, 1, ink), px(10, 4, 1, 1, gold))
      const lens = c('#cfe8ff')
      parts.push(px(3, OY + 1, 3, 2, lens), px(7, OY + 1, 3, 2, lens), px(6, OY + 1, 1, 1, ink), px(3, OY + 2, 3, 1, c('#8fb8e0')), px(7, OY + 2, 3, 1, c('#8fb8e0')))
      eyes()
      parts.push(px(5, OY + 4, 1, 1, red), px(7, OY + 4, 1, 1, red), px(6, OY + 4, 1, 1, c('#8b1e1e')))
      parts.push(px(11, 4, 2, 3, c('#f3ead2')), px(11, 5, 2, 1, red))
      break
    }
    case 'mage': {
      // the mage: pointed starred hat, gem staff in the right claw, sparks
      const hat = c('#6d4ac7')
      parts.push(px(7, 0, 1, 1, hat), px(6, 1, 2, 1, hat), px(5, 2, 3, 1, hat), px(4, 3, 5, 1, hat), px(2, 4, 9, 1, c('#4d2f9e')), px(6, 3, 1, 1, gold))
      parts.push(px(12, 2, 1, 5, wood), px(11, 0, 2, 2, c('#8b5cf6')), px(12, 0, 1, 1, c('#c4b5fd')))
      parts.push(px(9, 0, 1, 1, white), px(3, 1, 1, 1, white))
      eyes()
      break
    }
    default:
      eyes()
  }
  const bob = o.animated
    ? `<animateTransform attributeName="transform" type="translate" values="0 0;0 -0.5;0 0" dur="${design === 'courier' ? '0.35s' : '0.7s'}" repeatCount="indefinite"/>`
    : ''
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${crabWidth(h)}" height="${h}" style="${SVG_ROOT_STYLE}" viewBox="0 -0.5 13 12.5" shape-rendering="crispEdges"><g>${bob}${parts.join('')}</g></svg>`
}

// --- Pane drawings (desktop: SVG; terminal: text) ---------------------------------------------

/** Level of a limit window against the alert thresholds of the options. */
export function limitLevel(percent: number, o: Pick<Options, 'limitWarn' | 'limitCritical'>): 'ok' | 'warn' | 'critical' {
  return o.limitCritical > 0 && percent >= o.limitCritical ? 'critical' : o.limitWarn > 0 && percent >= o.limitWarn ? 'warn' : 'ok'
}
export const LIMIT_HEX = { ok: STATE_HEX.done, warn: STATE_HEX.input, critical: STATE_HEX.error } as const
export const LIMIT_HEIGHT = 16

/**
 * Limit gauge: pill track, solid fill in the color of the level, the forecast up to the reset hatched in the
 * color of the level it would reach, one tick per alert threshold. `uid` suffixes the ids when several gauges
 * share one document (preview page); each `Svg` of the pane is isolated.
 */
export function limitSvg(l: Limit, width: number, o: Pick<Options, 'limitWarn' | 'limitCritical'>, uid = ''): string {
  const W = Math.max(40, Math.floor(width))
  const H = LIMIT_HEIGHT
  const f = forecast(l)
  const used = Math.max(0, Math.min(100, l.percentUsed))
  const projected = f.atReset === null ? used : Math.max(used, Math.min(100, f.atReset))
  const hex = LIMIT_HEX[limitLevel(l.percentUsed, o)]
  const projHex = LIMIT_HEX[limitLevel(f.atReset ?? 0, o)]
  const x = (p: number) => Math.round((W * p) / 100)
  const tick = (p: number, color: string) => (p > 0 && p < 100 ? `<rect x="${x(p) - 1}" y="0" width="2" height="${H}" fill="${color}" fill-opacity="0.8"/>` : '')
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" style="${SVG_ROOT_STYLE}">` +
    `<defs><clipPath id="lc${uid}"><rect width="${W}" height="${H}" rx="${H / 2}"/></clipPath>` +
    `<pattern id="lh${uid}" width="6" height="6" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="3" height="6" fill="${projHex}" fill-opacity="0.5"/></pattern></defs>` +
    `<g clip-path="url(#lc${uid})"><rect width="${W}" height="${H}" fill="#8a8a87" fill-opacity="0.2"/>` +
    (projected > used ? `<rect x="${x(used)}" width="${x(projected) - x(used)}" height="${H}" fill="url(#lh${uid})"/>` : '') +
    `<rect width="${x(used)}" height="${H}" fill="${hex}"/></g>` +
    tick(o.limitWarn, LIMIT_HEX.warn) +
    tick(o.limitCritical, LIMIT_HEX.critical) +
    `</svg>`
  )
}

/** Cells of a terminal limit gauge: used, forecast up to the reset, free; they add up to `width`. */
export function limitCells(l: Limit, width: number): { used: number; projected: number; free: number } {
  const w = Math.max(1, Math.floor(width))
  const f = forecast(l)
  const used = Math.round((Math.max(0, Math.min(100, l.percentUsed)) / 100) * w)
  const upTo = f.atReset === null ? used : Math.max(used, Math.round((Math.min(100, f.atReset) / 100) * w))
  return { used, projected: upTo - used, free: w - upTo }
}

/** Terminal limit gauge: `█` used, `▒` forecast up to the reset, `░` free. */
export function limitGauge(l: Limit, width: number): string {
  const c = limitCells(l, width)
  return '█'.repeat(c.used) + '▒'.repeat(c.projected) + '░'.repeat(c.free)
}

/** Colors of the parts that count toward the limits, in the order they are stacked. */
export const USAGE_HEX = { cacheWrite: '#a78bfa', output: '#d97757', input: '#60a5fa' } as const

/**
 * Stacked usage bar: cache written, output, input, scaled against `max` (the heaviest agent or model of the
 * session), so that two bars of the pane compare. Cache reads do not count toward the limits: not drawn.
 */
export function usageSvg(t: Tokens, width: number, max: number, o: { height?: number; uid?: string } = {}): string {
  const W = Math.max(20, Math.floor(width))
  const H = o.height ?? 8
  const uid = o.uid ?? ''
  const k = max > 0 ? W / max : 0
  const parts = (['cacheWrite', 'output', 'input'] as const).map(p => ({ w: t[p] * k, fill: USAGE_HEX[p] }))
  let x = 0
  const rects = parts.map(p => {
    const r = p.w > 0 ? `<rect x="${+x.toFixed(2)}" width="${+p.w.toFixed(2)}" height="${H}" fill="${p.fill}"/>` : ''
    x += p.w
    return r
  })
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" style="${SVG_ROOT_STYLE}">` +
    `<defs><clipPath id="uc${uid}"><rect width="${Math.max(0, Math.min(W, +x.toFixed(2)))}" height="${H}" rx="${H / 2}"/></clipPath></defs>` +
    `<rect width="${W}" height="${H}" rx="${H / 2}" fill="#8a8a87" fill-opacity="0.15"/>` +
    `<g clip-path="url(#uc${uid})">${rects.join('')}</g></svg>`
  )
}

/** Cells of a terminal usage bar, stacked as `usageSvg` and scaled against `max`; they add up to `width`. */
export function usageCells(t: Tokens, width: number, max: number): { cacheWrite: number; output: number; input: number; free: number } {
  const w = Math.max(1, Math.floor(width))
  const k = max > 0 ? w / max : 0
  // cumulative rounding: the parts add up to the rounded total
  const a = Math.min(w, Math.round(t.cacheWrite * k))
  const b = Math.min(w, Math.round((t.cacheWrite + t.output) * k))
  const c = Math.min(w, Math.round((t.cacheWrite + t.output + t.input) * k))
  return { cacheWrite: a, output: b - a, input: c - b, free: w - c }
}

/** Width in px of `columns` text columns of a remote surface (same scale as the band's bar). */
export const columnsPx = (columns: number): number => Math.max(24, Math.floor(columns * COL_PX))

/** `14:05` in the local time zone; with `withDay`, `10-08 14:05`. */
export function localClock(ms: number, withDay = false): string {
  const d = new Date(ms)
  const p = (n: number) => String(n).padStart(2, '0')
  return `${withDay ? `${p(d.getMonth() + 1)}-${p(d.getDate())} ` : ''}${p(d.getHours())}:${p(d.getMinutes())}`
}

/** The foldable sections of the pane; the folded ones are kept in a state shared by every surface. */
export const PANE_SECTIONS = ['limits', 'agents', 'prompts', 'usage'] as const
export type PaneSection = (typeof PANE_SECTIONS)[number]
export const toggleFold = (folded: readonly string[], id: string): string[] =>
  folded.includes(id) ? folded.filter(x => x !== id) : [...folded, id]

/** Agent type without its plugin prefix: `orchestration:executor-low` → `executor-low`. */
export const agentName = (agent: string): string => agent.replace(/^[^:]+:/, '')

/** Third line of an agent card: its type, how it runs (resumed, forked) and the prompt that launched it. */
export function agentKind(r: AgentRun): string {
  if (r.id === MAIN) return `${r.agent} · session`
  const how = r.resumes > 0 ? ` · ${INSTANCE_LABEL.resumed} ×${r.resumes + 1}` : r.instance !== 'new' ? ` · ${INSTANCE_LABEL[r.instance]}` : ''
  return `${agentName(r.agent)}${how} · #${r.promptIndex}`
}
