"""Ingestion walk filters (vendor / minified / generated), rel_path storage,
and the CodeChunk full-text index migration.

Runs against a live FalkorDB (inside the mcp container) using the disposable
`gid` fixture from conftest.  Embedding is monkeypatched — no model load.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from server import ingestion  # noqa: E402
from server.db import get_graph  # noqa: E402
from server.schema import ensure_schema  # noqa: E402


# ---------------------------------------------------------------------------
# Fixture repo
# ---------------------------------------------------------------------------

@pytest.fixture()
def repo(tmp_path: Path) -> Path:
    # normal file — must be ingested
    (tmp_path / "app.py").write_text(
        "def normal_fn():\n    \"\"\"A normal function.\"\"\"\n    return 42\n"
    )
    # minified by name
    (tmp_path / "lib.min.js").write_text("function a(){return 1}\n")
    # minified by content: single enormous first line
    (tmp_path / "bundle.js").write_text(
        "function b(){return 2};" * 200 + "\n"  # first line ~4800 chars
    )
    # generated marker (C#-style SOAP Reference.cs)
    (tmp_path / "Reference.cs").write_text(
        "//------------------------------------------------------------\n"
        "// <auto-generated>\n"
        "//     This code was generated by a tool.\n"
        "// </auto-generated>\n"
        "//------------------------------------------------------------\n"
        "namespace Ws { public class C { public int M() { return 1; } } }\n"
    )
    # vendor dirs — must be pruned
    for vendor in ("packages", "bower_components", "third_party", "Pods"):
        d = tmp_path / vendor / "dep"
        d.mkdir(parents=True)
        (d / "vendored.py").write_text("def vendored_fn():\n    return 0\n")
    return tmp_path


def _walk(repo: Path, counters: dict | None = None) -> list[str]:
    return [p for p, _ext, _code in ingestion.iter_source_files(str(repo), counters)]


# ---------------------------------------------------------------------------
# Walk filters
# ---------------------------------------------------------------------------

def test_normal_file_included(repo: Path):
    paths = _walk(repo)
    assert any(p.endswith("app.py") for p in paths)


def test_minified_by_name_excluded(repo: Path):
    paths = _walk(repo)
    assert not any(p.endswith("lib.min.js") for p in paths)


def test_minified_by_content_excluded(repo: Path):
    paths = _walk(repo)
    assert not any(p.endswith("bundle.js") for p in paths)


def test_generated_marker_excluded(repo: Path):
    paths = _walk(repo)
    assert not any(p.endswith("Reference.cs") for p in paths)


def test_vendor_dirs_excluded(repo: Path):
    paths = _walk(repo)
    assert not any("vendored" in p for p in paths)


def test_exclusions_are_counted(repo: Path):
    counters: dict = {}
    _walk(repo, counters)
    assert counters["skipped_vendor"] >= 4          # packages, bower_components, third_party, Pods
    assert counters["skipped_minified"] >= 2        # lib.min.js + bundle.js
    assert counters["skipped_generated"] >= 1       # Reference.cs


def test_generated_marker_variants():
    for marker in (
        b"// Code generated by protoc-gen-go. DO NOT EDIT.\n",
        b"# This file was automatically generated by SWIG\n",
        b"/* <auto-generated /> */\n",
    ):
        assert ingestion._is_generated_content(marker + b"def f(): pass\n")
    assert not ingestion._is_generated_content(b"def normal():\n    return 1\n")


def test_minified_content_heuristic():
    assert ingestion._is_minified_content(b"x" * 3000 + b"\n")
    # dense file, few newlines
    assert ingestion._is_minified_content((b"y" * 900 + b"\n") * 10)
    normal = b"\n".join(b"line %d" % i for i in range(200))
    assert not ingestion._is_minified_content(normal)


# ---------------------------------------------------------------------------
# ingest_repo: counters in the returned dict + rel_path on chunks
# ---------------------------------------------------------------------------

@pytest.fixture()
def fake_embed(monkeypatch):
    monkeypatch.setattr(ingestion, "embed", lambda text, purpose: [0.0] * 768)


def test_ingest_repo_counts_and_rel_path(repo: Path, gid: str, fake_embed):
    stats = ingestion.ingest_repo(gid, str(repo))
    assert stats["skipped_vendor"] >= 4
    assert stats["skipped_minified"] >= 2
    assert stats["skipped_generated"] >= 1
    assert stats["total"] >= 1  # normal_fn was chunked

    g = get_graph(gid)
    res = g.query(
        "MATCH (c:CodeChunk {group_id: $gid}) RETURN c.symbol, c.rel_path, c.valid",
        {"gid": gid},
    )
    rows = res.result_set
    assert rows, "expected at least one CodeChunk"
    by_symbol = {r[0]: r for r in rows}
    assert "app.normal_fn" in by_symbol
    assert by_symbol["app.normal_fn"][1] == "app.py"  # relative, normalized
    assert all(r[2] is True for r in rows)
    # nothing from vendor / minified / generated made it in
    assert not any("vendored" in (r[1] or "") for r in rows)


def test_reingest_restores_validity_and_backfills_rel_path(repo: Path, gid: str, fake_embed):
    """Hash-gating invariant: unchanged chunks must come back valid=true, and
    pre-migration chunks (no rel_path) get rel_path backfilled without re-embed."""
    ingestion.ingest_repo(gid, str(repo))
    g = get_graph(gid)
    # simulate cleanup invalidation + a pre-migration chunk (rel_path removed)
    g.query(
        "MATCH (c:CodeChunk {group_id: $gid}) SET c.valid = false, c.rel_path = NULL",
        {"gid": gid},
    )
    stats = ingestion.ingest_repo(gid, str(repo))
    assert stats["embedded"] == 0          # hash-gated: nothing re-embedded
    assert stats["skipped"] >= 1
    res = g.query(
        "MATCH (c:CodeChunk {group_id: $gid}) RETURN c.valid, c.rel_path",
        {"gid": gid},
    )
    assert res.result_set
    for valid, rel in res.result_set:
        assert valid is True
        assert rel  # backfilled


# ---------------------------------------------------------------------------
# Machine-independent identity: the same repo checked out at two different
# absolute paths must produce the same nodes, not duplicates. This is what
# lets a second machine (or a server-side git mirror) share one graph.
# ---------------------------------------------------------------------------

def test_chunk_identity_is_independent_of_checkout_path(
    repo: Path, tmp_path_factory, gid: str, fake_embed,
):
    import shutil

    ingestion.ingest_repo(gid, str(repo))
    g = get_graph(gid)

    def _snapshot() -> set[tuple[str, str]]:
        res = g.query(
            "MATCH (c:CodeChunk {group_id: $gid, valid: true}) RETURN c.id, c.path",
            {"gid": gid},
        )
        return {(r[0], r[1]) for r in res.result_set}

    first = _snapshot()
    assert first
    assert all(not p.startswith("/") for _, p in first), "paths must be repo-relative"

    # Same content, different checkout location — as another machine would have it.
    other = tmp_path_factory.mktemp("elsewhere") / "clone"
    shutil.copytree(repo, other)
    stats = ingestion.ingest_repo(gid, str(other))

    assert stats["embedded"] == 0, "same content must stay hash-gated across checkouts"
    assert _snapshot() == first, "a different checkout path must not fork the nodes"


# ---------------------------------------------------------------------------
# Mark-and-sweep: a full scan owns the whole chunk set
# ---------------------------------------------------------------------------

def test_sweep_invalidates_chunks_of_deleted_file(repo: Path, gid: str, fake_embed):
    (repo / "gone.py").write_text("def doomed_fn():\n    return 1\n")
    ingestion.ingest_repo(gid, str(repo))
    g = get_graph(gid)

    def _valid_symbols() -> set[str]:
        res = g.query(
            "MATCH (c:CodeChunk {group_id: $gid, valid: true}) RETURN c.symbol",
            {"gid": gid},
        )
        return {r[0] for r in res.result_set}

    assert "gone.doomed_fn" in _valid_symbols()

    (repo / "gone.py").unlink()
    ingestion.ingest_repo(gid, str(repo))

    symbols = _valid_symbols()
    assert "gone.doomed_fn" not in symbols, "chunk of a deleted file must be swept"
    assert "app.normal_fn" in symbols, "surviving chunks must stay valid"


def test_sweep_deletes_pre_migration_absolute_path_chunks(repo: Path, gid: str, fake_embed):
    """Chunks keyed by an absolute path predate repo-relative ids and can never
    be re-derived — a full scan removes them instead of leaving them forever."""
    g = get_graph(gid)
    g.query(
        "CREATE (:CodeChunk {id: 'legacy1', group_id: $gid, path: '/old/abs/app.py', "
        "symbol: 'app.normal_fn', valid: true})",
        {"gid": gid},
    )
    stats = ingestion.ingest_repo(gid, str(repo))

    assert stats["deleted_pre_migration"] >= 1
    res = g.query("MATCH (c:CodeChunk {id: 'legacy1'}) RETURN count(c)")
    assert res.result_set[0][0] == 0


def test_sweep_skipped_when_scan_yields_nothing(repo: Path, gid: str, fake_embed):
    """An empty walk means the scan failed, not that the repo is empty — it must
    not wipe the index."""
    ingestion.ingest_repo(gid, str(repo))
    g = get_graph(gid)

    empty = repo / "empty_tree"
    empty.mkdir()
    stats = ingestion.ingest_repo(gid, str(empty))

    assert stats["total"] == 0
    assert stats["invalidated"] == 0
    res = g.query(
        "MATCH (c:CodeChunk {group_id: $gid, valid: true}) RETURN count(c)",
        {"gid": gid},
    )
    assert res.result_set[0][0] > 0, "a failed scan must not invalidate the index"


# ---------------------------------------------------------------------------
# Full-text index migration (symbol,signature → symbol,signature,rel_path)
# ---------------------------------------------------------------------------

def _codechunk_fulltext_fields(g) -> set[str]:
    res = g.query("CALL db.indexes()")
    for row in res.result_set:
        if row[0] == "CodeChunk":
            return {p for p, kinds in dict(row[2]).items() if "FULLTEXT" in kinds}
    return set()


def test_fulltext_migration_adds_rel_path(gid: str):
    g = get_graph(gid)
    # simulate a pre-migration graph: old fulltext index without rel_path
    g.query("CALL db.idx.fulltext.createNodeIndex('CodeChunk', 'symbol', 'signature')")
    assert _codechunk_fulltext_fields(g) == {"symbol", "signature"}

    ensure_schema(gid)
    assert _codechunk_fulltext_fields(g) == {"symbol", "signature", "rel_path"}


def test_fulltext_matches_path_tokens(gid: str):
    ensure_schema(gid)
    g = get_graph(gid)
    g.query(
        "CREATE (:CodeChunk {id: 'ft1', group_id: $gid, symbol: 'Editor.Save', "
        "signature: 'public void Save()', rel_path: 'CuteSoft_Client/CuteEditor/Editor.cs', "
        "valid: true})",
        {"gid": gid},
    )
    res = g.query(
        "CALL db.idx.fulltext.queryNodes('CodeChunk', 'CuteSoft_Client') "
        "YIELD node RETURN node.id"
    )
    assert ["ft1"] in res.result_set


def test_ensure_schema_idempotent_after_migration(gid: str):
    ensure_schema(gid)
    ensure_schema(gid)  # second call must not error or drop fields
    g = get_graph(gid)
    assert {"symbol", "signature", "rel_path"} <= _codechunk_fulltext_fields(g)
